republik/plattform

.husky/pre-commit
.prettierrc
package.json
yarn.lock

Add lint-staged configuration to run prettier over all staged `{js,ts,tsx}` files & update husky accordingly.

Configure Husky to run lint-staged

---

apps/www/pages/dialog.js

Remove the discussion-icon next to the "Aktive Debatten" heading. It is removed for two reasons:
1. Consistent headings on the page
2. The Icon had faulty styling when using darkmode (see screenshot below)
Instead of removing the icon completely, it might an option to add it next to the green numbers for each active debate. That way it would be consistent compared to how the amount of comments are displayed, for example, on the front. (See screenshot below for a comparison)

fix: Active Debate section - DisucssionIcon

---

.husky/commit-msg

@patrickvenetz could you please check if this also fixes the issues that you experienced?

chore(commitlint): ignore node-version requirements when running commitlint

---

apps/www/components/Notifications/SubscribedDocuments.js

Related issue https://github.com/republik/plattform/issues/7
Fix a color-error in the notification-settings section-titles, by using the format mapping that can be enabled in the `colorscheme.set` method.

www: fix notification settings section-titles

---

apps/www/components/Discussion/CommentContainers/CommentContainer.tsx
packages/backend-modules/discussions/graphql/resolvers/Discussion/userCanComment.js

Closes #5 
Don't pass the reply-handler to the CommentNode if the discussion is closed. (Line 112)

Update userCanComment resolver to return false if the discussion has been closed.

---

apps/www/components/Discussion/DiscussionComposer/DiscussionComposer.tsx
apps/www/components/Discussion/graphql/queries/PreviewCommentQuery.graphql.ts
apps/www/components/Discussion/helpers/usePreviewCommentHandler.ts
packages/styleguide/src/components/Discussion/Composer/CommentComposer.js

Fixes #6 
The tag value is now passed to the preview-handler and no initial tag-value is set, if a composer is opened to compose a reply.

Send tag value when requesting comment preview

---

apps/admin/package.json
apps/publikator/package.json
apps/www/package.json
package.json
packages/styleguide/package.json
yarn.lock

With #15 a yarn-error was introduced. In this PR I installed lint-staged inside the workspace repository with the command `yarn add -D -W lint-staged`. This broke all subsequent installs of dependencies.
After quite sometime I managed to fix this issue by manually removing lint-staged from all workspace-packages and installing it only inside the root-workspace.

Fix error when installing dependencies inside the workspace packages

---

packages/styleguide/src/components/Discussion/Composer/CommentComposer.js
packages/styleguide/src/components/Discussion/Composer/CommentDraftHelper.js

Some versions of safari have a `localStorage` object but no `getItem` function.
While some `readDraft` were wrapped in a try block, a `readDiscussionCommentDraft` was not (my fault). However I think in code paths we ignore broken local storage we should do the try catch everywhere we interact with it instead of assuming that our function is wrapped in a silent try catch as a whole. Wrapping the whole function also hides coding errors that are unrelated to local storage being available.

fix(Discussion): unsafe localStorage.getItem

---

package.json

Surprisingly this works even though ESLint isn't actually installed inside the the root-package.
(Small fix to get ESlint running again before unifying the configurations)

Add eslint fix to lint-staged

---

packages/styleguide/package.json
packages/styleguide/tsconfig.dist.json
packages/styleguide/tsconfig.json

Back when we used rollup, a plugin handled the generation of the type declarations.
Due to the removal of rollup, types were no longer emitted. 
With this PR the config was updated to emit type declarations again. 
Also source-maps for both the JS and the TS declaration will now be generated when running dev:lib.

Styleguide emit type declarations

---

turbo.json

turbo cache does not play well with current setup of backend-modules. It does not understand which files ought to be cached compiled via `tsc` while building.

build: disables turbo cache on backend-modules

---

apps/www/components/Testimonial/List.js
apps/www/lib/translations.json
apps/www/pages/community.js
packages/backend-modules/republik/graphql/resolvers/_queries/statements.js

This introduces a 404 status code and error message if a community focus id is not returned.
Additionally focus are no longer returned from the backend if the user no longer has an active member role. This matches the behaviour in the list where past members are already filtered out.

Fix Statement Focus

---

apps/www/components/Access/Campaigns/ShareChart.js
apps/www/lib/translations.json
apps/www/lib/utils/format.js
apps/www/pages/cockpit.js

Before and after:
The current version has following problem:
- «Gewonnene Verlegerinnen» is inaccurate because donations and gifts count too
- it says «letzten vier Wochen» but displays 31 days
- «25 Personen für die Republik entschieden» those 25 pledge events are often from access grants that are not visible on the chart
- no foot note with data date and time, no explanation what counts as «Gewonnene»
Not 100% sure about the wording, especially the denglisch «Konversionsrate».
For the record and to understand how I got to the new chart, here a few wip intermediate screenshots:
| action | screenshot |
|---|---|
| calculate max rate in the last 60 days | <img width="868" alt="Screenshot 2022-02-23 at 18 50 14" src="https://user-images.githubusercontent.com/410211/155389040-51271dbf-3e7c-4e …

Improve Share Chart

---

packages/eslint-config-backend/index.js

A faulty configuration inside the backend eslint-configuration caused the tsconfig of the individual packages to not be resolved correctly.
https://user-images.githubusercontent.com/30313631/155778764-07746447-0f2f-4fbd-a01a-b039c1264633.mp4
1. Add this line to backend-modules/auth/index.ts
```ts
declare const loggedInUsername: string;
const users = [
{ name: "Oby", age: 12 },
{ name: "Heera", age: 32 },
];
const loggedInUser = users.find((u) => u.name === loggedInUsername);
console.log(loggedInUser.age);
```
You should see that `loggedInUser.age` is highlighted since it might be null.
2. Update the backend tsconfig to `"strictNullChecks": false` (as in the video)
3. You should now no longer see the above mentioned error being highlighted
WebStorm: 2021.3.2
VSCode: V1.64.2
VSCode Eslint …

Fix faulty project pattern in eslint-config-backend

---

apps/www/components/ActionBar/index.js

Fixes overlong ActionBar when audio and reading position are both present. Scopes the fix to only concern SeriesEpisode-ActionBar
Result:

fix(ActionBar): flexWrap in seriesEpisode

---

packages/backend-modules/discussions/graphql/resolvers/Discussion/comments.js

Fix an error that caused focus-urls to break when sharing a reply.
(After spending the better part of a day trying to pin-point the issue, we managed to figure out that is caused by due to the parent-comment being filtered out since they were not assigned a topLevel value, that caused them to remain in the list of initially returned comments)

Fix focused comment not loading if it's not inside the initial comment query result

---

packages/styleguide/src/components/Overlay/Overlay.tsx

Just like on all other websites, the user should be able to close overlays by pressing escape. 🤖 
(Also added missing prop-types to the validator of the OverlayRenderer)

Allow closing overlays by pressing the ESC key

---

apps/publikator/components/Derivatives/index.js
packages/backend-modules/publikator/graphql/resolvers/Commit.js
packages/backend-modules/publikator/graphql/resolvers/_mutations/generateDerivative.js
packages/backend-modules/publikator/lib/Derivative/SyntheticReadAloud.ts

Minor enhancements to Synthetic Read Aloud
- Publikator: Show latest derivative as CTA
- Publikator: Do not render derivative CTA if `meta.audioSource*` is present

Minor enhancements to Synthetic Read Aloud

---

apps/www/components/Audio/MediaProgress.js
apps/www/lib/playbackRate.js
packages/styleguide/src/components/AudioPlayer/ExpandableAudioPlayer.tsx
packages/styleguide/src/components/AudioPlayer/Player.js
packages/styleguide/src/components/AudioPlayer/docs.md

The createPersistedState hook causes a constant re-render of the MediaProgressProvider which in turn caused the article progress to re-render and so forth. For this use case static `localStorage.getItem` and `localStorage.setItem` are much better. Later we shall refactor the players to use a proper media context.
iOS lazy loads audio and we used to work around that in a bad and buggy way. Now we respect that but trigger an explicit `audioElement.load()` if we have a media position or it's auto play. `loading` (waits for meta data) is now separate from `canSetTime` (`canPlay` event, used to be `playEnabled`). This should prevent buggy `currentTime` sets before the audio is ready.
There is now an example for the source error in the overview mode and the retry button actually works.

Audio Player: Perf Local Progress & Better State Handling

---

packages/backend-modules/auth/lib/challenges/AccessTokenChallenge.js
packages/backend-modules/auth/lib/challenges/AppChallenge.js
packages/backend-modules/auth/lib/challenges/EmailCodeChallenge.js
packages/backend-modules/auth/lib/challenges/EmailTokenChallenge.js
packages/backend-modules/translate/translations.json

This Pull Request address [a report from our bug bounty program](https://app.gobugfree.com/account/programs/republik/submissions/KAYPWRGlBq) which could have triggered a vast amount of sign-in emails.
It limits `mutation signIn` with type `EMAIL_TOKEN` to 5 per hour (this imitating an existing rate limit with type `EMAIL_CODE`). It uses a sliding window to open up slots to request more sign-in emails.
It furthermore limits type `APP` – authorizing via App – to 5 requests per 10 minutes.
Once a limit is reached, a `TokensExceededError` is thrown a human readable error message.
It ever so slightly refactors token counting: count tokens instead of fetching them if payloads are not required to generate a new token.
**A screenshot with a sample error message**

Limit pending sign-in tokens

---

apps/www/components/Pledge/Submit.js
apps/www/lib/translations.json

As of now the contact-form was only shown if both the me and customMe are not present. However with problesen, a me-object might exist but the first and lastname are missing.
This PR adds an additional check that shows the contact-form even if me is present, when fName or lName are missing

fix(www/Checkout): show the contact-form if a user has no fname or lname

---

packages/backend-modules/mail/express/mailchimp.js
packages/backend-modules/mail/migrations/sqls/20220413113433-mailchimp-log-index-email-down.sql
packages/backend-modules/mail/migrations/sqls/20220413113433-mailchimp-log-index-email-up.sql
packages/backend-modules/migrations/migrations/20220413113433-mailchimp-log-index-email.js

This Pull Request checks on MailChimp Webhook event type "subscribe" if latest record in `mailchimLog` for an email address is type "cleaned". If so, it will call `enforceSubscription` and thus updating and restoring interests.
It should resolve a race condition (we hot fixed in 57701d787eb6f2075af936451033cbd41f90d933).

feat(mail): restore interests on Mailchimp if last event was type "cleaned"

---

apps/publikator/components/Publication/Current.js
apps/publikator/components/editor/modules/meta/ArticleRecommendations/ArticleRecommendationItem.js

This Pull Request should resolve caching errors when opening a doc via repo list.
It was caused due to missing identifier (`id`) on meta.format queries which let to a caching error (invariant violation).
Added to https://github.com/republik/plattform/pull/95/files#diff-fa5d18ff5fd5ad40adb95829b7d4ab87cbb2aa73588976841f01e48e898f07f3R52.
And while checking, found [this one lacking an identifier, too](https://github.com/republik/plattform/pull/95/files#diff-e3d148c22ad217e6565b38a1216b38ffc08f949b5f30825e8abce485cecbeb80R232) – which might have caused an issue when linking recommendation documents with a format; while Repo-URL is correct and data got fetched, it refused to render recommendation properly. (Might be of interest to @trm217.)

fix(publikator): query Document.id on meta.format to avoid invariant violation

---

apps/publikator/components/editor/modules/meta/ArticleRecommendations/ArticleRecommendationItem.js
apps/publikator/components/editor/modules/meta/ArticleRecommendations/ArticleRecommendations.js
apps/publikator/components/editor/utils/RepoSearch.js
packages/styleguide/src/components/Form/Autocomplete.js

- Only show the Publikator Link when a document was found.
- AutoFocus on RepoSearch input when adding an article to the recommendations

Slight improvements to Publikator Recommendations editor

---

apps/admin/components/Payments/List/Table.js

This Pull Request will render `Address.name` in Admin-Tool payments list if string differs from a users name. It helps Finance to find payments easier.

fix(admin): render address name in payments list

---

packages/backend-modules/mail/express/mailchimp.js

This Pull Request will subscribe users to editorial newsletters if they resubscribe after they were flagged as cleaned by MailChimp

fix(mail): subscribe to editorial newsletters when resubscribing to MailChimp

---

packages/styleguide/src/components/Chart/ChartContext.js
packages/styleguide/src/components/Chart/ScatterPlots.docs.md
packages/styleguide/src/components/Chart/ScatterPlots.js

The `size` property of the chart config is usually passed to `Breakout` for breaking out of the normal size. However for scatter plots the `size` prop was also used for the point size within the plot. This lead to conflicts when we e.g. wanted a `narrow` scatter plot with a `size` from the data column `rate`. We worked around this by usually renaming the data column to `narrow` ;-) The new `pointSize` prop (with a fallback to `size` for backwards compat) should make such workaround no longer necessary. I also explored introducing a `breakoutSize` prop but that was way more intrusive.

fix(ScatterPlots): avoid conflict of point size and breakout size

---

.gitignore
apps/www/lib/translations.json

fix "Mehr Informationen zur Republik." link in the Abo-kaufen paynote.

fix(Paynote): fix doubly escaped characters

---

apps/api/.env.example
packages/backend-modules/base/express/graphql.js
packages/backend-modules/documents/graphql/resolvers/Document.js
packages/backend-modules/documents/graphql/resolvers/_queries/document.js
packages/backend-modules/documents/graphql/resolvers/_queries/documents.js
packages/backend-modules/documents/graphql/schema.js
packages/backend-modules/documents/lib/process.js
packages/backend-modules/documents/lib/process.u.jest.js
packages/backend-modules/documents/lib/resolve.js
packages/backend-modules/documents/lib/restrictions.js
packages/backend-modules/search/graphql/resolvers/_queries/search.js
packages/backend-modules/search/graphql/schema.js
packages/backend-modules/search/lib/Documents.js
packages/backend-modules/search/lib/options.js
packages/backend-modules/subscriptions/lib/Subscriptions.js

Allows to request fully resolved documents without being signed in.
We plan to use it for member cache in the front end and potential site maps.
To test locally make sure to set following env:
```
DOCUMENTS_RESTRICT_TO_ROLES=member
DOCUMENTS_LINKS_RESTRICTED=/
DOCUMENTS_API_KEYS=[{"key":"long-safe-secret","name":"frontend"}]
DOCUMENTS_SAMPLES_REPO_IDS=republik/format-wochenende-newsletter
DOCUMENTS_SAMPLES=3
```
And use this query for example:
```
{
document(path: "/", apiKey: "long-safe-secret") {
children(first: 3) {
nodes {
body
}
}
}
documents(feed: true, apiKey: "long-safe-secret", first: 3) {
totalCount
nodes {
meta {
title
}
}
}
search(processor: formatFeedSamples, filter: {
format: "republik/format-wochenende-newsletter"
}, first: 5, apiKey: "long-safe-secret") {
totalCount
nodes …
```

feat: document api keys

---

apps/www/components/Footer/index.js

Previously the version number of the app could only be seen in the phone settings or in the app-/play-store.
With this PR the version number will be shown at the very bottom of the footer. (right aligned just as the open source link directly above the version number.

Render the App version in the footer

---

packages/styleguide/src/components/Overlay/Overlay.tsx

On any mouse-down event on the modal, if the mouse was then moved out of the modal and onto the backdrop, on release the modal would close.
This was due to the parent element-registering the click on it's self rather than on it's child.
By moving the onClick-handler, that closes the modal, onto a sibling element of the modal this issue can be circumvented.
https://user-images.githubusercontent.com/30313631/169085199-042693a6-9cbe-4fab-9f4b-c08b88fca5a8.mov
https://user-images.githubusercontent.com/30313631/169085709-9a7d7f45-e314-4b16-8d8c-529c188fae29.mov

fix Overlay closing when mouse is released over backdrop

---

apps/www/components/Events/List.js
apps/www/components/Frame/Meta.js
apps/www/components/Marketing/Pledge.js
apps/www/components/Pledge/Form.js
apps/www/components/Profile/Page.js
apps/www/lib/translations.json
apps/www/pages/aktionariat.js
apps/www/pages/rubriken.js
apps/www/pages/wahltindaer/index.js

- Fixes Markting index having its meta title overwritten by Pledge/Form component on that page.
- Hormonizes titles (usually append "– Republik") or return title as is (`pageTitle`).
Fixes #135

A11Y: Seitentitel

---

apps/www/components/Article/ReadAloudInline.tsx

Fixes vertical alignment being off on mobile when article is read by human.
Result:

fix(ReadAloudInline): fix vertical alignment

---

apps/www/components/Article/Page.js
apps/www/components/Article/PayNote.js
apps/www/components/StatusError/index.js
apps/www/lib/context/UserAgentContext.tsx
apps/www/lib/translations.json
apps/www/lib/withInNativeApp.js
apps/www/next.config.js
apps/www/pages/[...path].tsx
apps/www/pages/install.js

We introduce a new `/install` route which roughly follows this logic:
```
- if iOS or Android
- if inNative App
- show marketing with probelese/front
- track visit (incl. utm)
- else
- track visit (incl. utm)
- redirect to App Store on iOS and Play Store on Android
- open app
- marketing with probelese
- track without utms (they are lost)
- show /probelesen in case page stays open or returning to browser
- else
- show /probelesen
- track visit (incl. utm)
```
Additionally following problems were fixed:
- #72 — this was rather tricky since we redirected in three ways to external urls: `next.config.js`, via `getStaticProps` returning a external url to the next redirect engine and in some cases via our `StatusError` component. Newly all external redirects go through our `StatusError` …

Redirect Mini Sprint

---

apps/www/components/Search/Form.js
packages/styleguide/src/components/Form/Field.tsx

According to the HTML5 standard, a form that contains a button while not other button with type=submit is present will be "clicked" once the form is submitted.
This caused our Search-Form, which only contains the search-field and the clear-button, to click the clear-button which then reset the page once the input was submitted.
Also updated the clear-icon button in the Field component to ensure that type='button' is also set there.
https://stackoverflow.com/questions/2825856/html-button-to-not-submit-form

fix(www/search): ensure clear-icon is not 'clicked' when submitting the form

---

apps/www/components/ActionBar/index.js
apps/www/components/Article/Page.js
apps/www/components/Article/ReadAloudInline.tsx
apps/www/lib/translations.json

**Before**
**After**
Upon deploy, add redirections beforehand
- /synthetic-read-aloud
- /read-aloud

feat(Article): append link to read aloud page

---

apps/admin/package.json
apps/www/package.json
packages/nextjs-apollo-client/package.json
yarn.lock

Lock version the version of `@apollo/client@^3.5.8` in `nextjs-apollo-client` & all apps that use it to `~3.5.10`. This will fix issues that first occurred in `@apollo/client@^3.6.0`

fix(nextjs-apollo-client): lock Apollo Client to ~3.5.10

---

packages/styleguide/src/components/ExpandableLink/ExpandableLinkCallout.tsx
packages/styleguide/src/components/ExpandableLink/shortenLink.test.js

fix(shortenLink): use string as such if not a url

---

packages/styleguide/src/components/Tabs/TabButton.tsx

Fixes #183.
Active link TabButtons now have `text-decoration: underline` styling unless `border={false}` is set.

fix(www/discussion): improve the order-by button-styling to better communicate the active state

---

apps/www/components/Account/NewsletterSubscriptions/index.js
apps/www/components/Account/enhancers.js
apps/www/components/Article/Page.js
apps/www/components/Auth/MacNewsletterSubscription.js
apps/www/components/Auth/Notification.js
apps/www/lib/translations.json
packages/backend-modules/mail/NewsletterSubscription.js
packages/backend-modules/mail/lib/getNewsletterSettings.js
packages/backend-modules/mail/templates/newsletter_request_CLIMATE.html
packages/backend-modules/mail/templates/newsletter_request_CLIMATE.txt
packages/backend-modules/mail/templates/newsletter_request_READALOUD.html
packages/backend-modules/mail/templates/newsletter_request_READALOUD.txt
packages/backend-modules/republik-crowdfundings/lib/Mail.js
packages/backend-modules/republik/.gitignore
packages/backend-modules/republik/graphql/resolvers/NewsletterSettings.js
packages/backend-modules/republik/graphql/resolvers/_mutations/requestNewsletterSubscription.js
packages/backend-modules/republik/graphql/schema-types.js
packages/backend-modules/republik/script/generateNewsletterHmac.ts
packages/backend-modules/translate/translations.json

This Pull Request adds two now Mailchimp segments to code base: `CLIMATE` (Klimalabor-Newsletter) and `READALOUD` («Hört, Hört» notification once released).
Both segments are invisible and won't be listed. API however returns subscription if queried by name:
```gql
{
user(slug: "someone") {
newsletterSettings {
subscriptions(name: CLIMATE) {
name
subscribed
}
}
}
}
``` 
This enables `Auth/NewsletterSubscriptions` to handle invisible Mailchimp segments if a name is provided (used when i. e. `Document.meta.newsletter.name` is set).
It then exposes `Auth/NewsletterSignUp` as a "Dynamic Component".
And it also refactors `Auth/Notifications` and `Auth/MacNewsletterSubscription` to allow for Mailchimp segment specific title and short text:

Newsletter signup, CLIMATE, READALOUD

---

packages/styleguide/src/components/ExpandableLink/ExpandableLinkCallout.tsx

Increase bottom-padding for mobile-viewports in the ExpandableLink callout.

fix(ExpandableLink): ensure enough bottom padding is given on mobile

---

apps/www/components/Account/NewsletterSubscriptions/index.js
apps/www/components/Account/enhancers.js
packages/backend-modules/assets/lib/Portrait.js

- `newsletterSettingsFragment` got an optional variable; while well intentioned, that was a shitty idea as it is hard to track down which arguments a fragment requires. [Reverted](https://github.com/republik/plattform/pull/194/commits/d182926c9d54e6d5c627c8e4b1fdcb5c8284796a).
- If `updateMe` failes (e.g. tel no too short), it will delete file a new portrait file, too. If there is no new portrait, `Portrait.del` return undefined instead of a resolved promise. Calling `Promise.del(xxx).catch()` caused an "undefined" error. [Fixed](https://github.com/republik/plattform/pull/194/commits/e8aadef1b6c4ad7f68e4ecf34aaa4b3bff2f5b09).

Fix newsletter resubscribe mutation, updateMe mutation

---

packages/backend-modules/statistics/lib/matomo/data.js
packages/backend-modules/statistics/script/report/daily.js

`stringifyNode` became asynchronous and requires a type. This Pull Request fixes that.
It allows flyer templates to be reported daily, too.

Fix daily statistics report

---

apps/www/components/Frame/Popover/Sections.js
apps/www/components/Sections/Index.js
packages/backend-modules/search/lib/options.js

This Pull Request changes `linkedDocuments` sub-query to return 0 nodes (`first: 0`) while still receiving `totalCount`.
Queries used on
- popover (sections with formats and their doc count)
- section page
It increases query response time.
**Before**
**After**

Improves Popover/Sections query loading speed

---

apps/admin/lib/apollo/index.ts
apps/admin/next.config.js
apps/publikator/lib/apollo/index.ts
apps/publikator/next.config.js
apps/www/components/Footer/index.js
apps/www/lib/apollo/index.ts
apps/www/lib/errors.js
apps/www/next.config.js
packages/nextjs-apollo-client/src/apollo/apolloClient.ts
packages/nextjs-apollo-client/src/index.ts

- feat(nextjs-apollo-config): allow passing a name and version to the apollo-client
- feat(www): pass buildId to public-runtime config and use it as client-version
- feat(clients): pass buildId to publicRuntimeConfig to pass to apollo-client

Pass identifiers to the apollo-client across our web-clients

---

apps/assets/server.js
packages/backend-modules/base/server.js

This Pull Request signals a client to cache a preflight request up to 24 hours.
Per default, preflight requests are cached only up to 5 seconds. Setting `maxAge` reduces response latency via www-app to API.
Example www-app posting to GraphQL API; it issues an "preflight req" _before_ posting to GraphQL API. Amount of "preflight req" would drop significantly once we signal browser to cache it.
It is safe to assume, CORS headers are unlikely to change in a breaking manner on assets server and GraphQL API server. 
Resources:
- https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age
- https://netbasal.com/reduce-response-latency-by-caching-preflight-requests-2c450b6f9cb6

fix: signal caching CORS preflight up to 24 hours

---

apps/www/components/Frame/Popover/FlyerNavLink.js
apps/www/components/Frame/Popover/Nav.js
apps/www/components/Frame/Popover/useFlyerMeta.js
apps/www/components/Frame/SecondaryNav.js
packages/styleguide/src/components/SeriesNav/SeriesNav.js

Our `NavLink`s to the flyer are rendered behind a `isMember` or  `hasOverviewNav` defined as `hasAccess && wantOverviewNav` check. But I ended up using a hook to query the current flyer path and used it atop of the `SecondaryNav` component which is rendered for everyone.
To remedy this I've introduced two measure:
1. move the hook to a new flyer nav link component that is only rendered when really needed
2. skip the query in the hook when `!hasAccess` and throw an error in dev that the hook should only be used in a sub tree that has access
Edit: also contains unrelated `SeriesNav` changes to fix react warnings I've noticed in my console while testing.

Reintroduce flyer path

---

apps/publikator/components/Calendar/Day.js
apps/publikator/components/ContentEditor/index.js
apps/publikator/components/Edit/EditView.js
apps/publikator/components/Edit/index.js
apps/publikator/lib/utils/calendar.js
apps/publikator/pages/flyer/[owner]/[repo]/preview.js
packages/styleguide/src/components/Editor/schema/flyer.tsx
packages/styleguide/src/components/Editor/schema/flyerEditor.tsx
packages/styleguide/src/components/Flyer/index.tsx

- Journal title when created through calendar is now based on publish date. (Before all journals were named `Journal` and that's not very enlightening.)
- progagate readonly props to the editor itself, hiding the toolbar when in readonly mode.
- adjust end salutation in template
- remove trennstrich when not rendering bgrüssung (now also shown as such in preview)
ring begrüssung (request from Oli)

More Journal Fixes

---

apps/publikator/components/ContentEditor/index.js
apps/publikator/components/Edit/EditView.js
apps/www/components/ActionBar/index.js
apps/www/components/Article/Flyer.js
apps/www/components/Article/Page.js
apps/www/lib/translations.json
packages/styleguide/src/components/Editor/Core/helpers/tree.ts
packages/styleguide/src/components/Editor/Core/index.tsx
packages/styleguide/src/components/Editor/Render/Context.tsx
packages/styleguide/src/components/Editor/config/elements/flyer/components/date.tsx
packages/styleguide/src/components/Editor/custom-types.d.ts
packages/styleguide/src/components/Editor/schema/flyer.tsx
packages/styleguide/src/components/Editor/test/tree-helpers.test.js
packages/styleguide/src/components/Flyer/Date.tsx
packages/styleguide/src/components/Flyer/index.tsx
packages/styleguide/src/components/TeaserFeed/Headline.js
packages/styleguide/src/components/Typography/styles.js
packages/styleguide/src/lib.ts

This PR fulfills several wishes from the art department.
1. Navigation above journal title. The navigation is now passed via a context to the journal itself, and displayed where the date used to be.
2. Share button just below the signature (no more footer tile).
3. Change share button-label

Journal nav

---

apps/www/components/Frame/Header.js
apps/www/components/Frame/Popover/Sections.js
apps/www/components/Frame/ProlongBox.js

`Frame/Header.js` is currently responsible that every not signed in article load triggers a `/angebote` prefetch including hitting the backend.
Also disable section and cancel link prefetch—those pages are rarely used or should be slow 😇 
Buy links in expanded navis still prefetch but only after clicking the navi. Pay notes do not use next link and have never prefetched.

Disable Prefetch in Header

---

apps/publikator/components/editor/modules/meta/AudioForm.js
apps/publikator/components/editor/utils/ImageCrop.js

Requires explicit interaction to add an image crop in metadata.
https://user-images.githubusercontent.com/20746301/194043124-6a4b1586-87c8-4bef-a706-68498e96f044.mov

fix(ImageCrop): prevent metdadata change without explicit recrop

---

apps/www/components/ActionBar/index.js
apps/www/components/Audio/AudioPlayerController.tsx
apps/www/components/Audio/AudioProvider.tsx
package.json

- You can now remove the active item from the action-bar just like any other item in the queue.
- The logic to advance the queue and load the next track is no longer now directly in the onQueueAdvance function. Previously this was done in a useEffect-hook which was removed.
- An extra hook was added to handle the edge case of loading a newly added item as the active item when the queue was empty before.

refactor(www/audio): allow removing the active-item from action-bar and refactor queue-advance

---

apps/www/components/Auth/TokenAuthorization.js
apps/www/components/Pledge/Merci.js

Currently when `unauthorizedSession` validates a token but the following `authorizeSession` fails for any reason (throws a error, including api timeout) the front end get's stuck in a loop and fires the `authorizeSession` mutation non stop. This change properly stops the automatic `authorizeSession` if it fails.
Additionally on a post pay account link it was possible that a sign in error continued to show after somebody signed in successfully. This is also fixed.

Fix Authorization Loop

---

packages/backend-modules/republik-crowdfundings/lib/scheduler/payments/fixtures/camt053noEntries.xml
packages/backend-modules/republik-crowdfundings/lib/scheduler/payments/parseCamt053.ts
packages/backend-modules/republik-crowdfundings/lib/scheduler/payments/parseCamt053.u.jest.ts

A CAMT.053 statement file usually contains transactions, one or moore `Ntry` records – and also lacking any `Ntry` records.
This Pull Request handles that.

Fix importPayments if CAMT.053 file contains no entries

---

apps/www/components/Audio/AudioPlayer/AudioPlayer.tsx

set background to 'default' instdead of 'overlay', making the separation of the UI elements more clear. The reason why it was set to 'default' is because in the native apps in expanded mode, the status bar is colored 'default' and thus it is necessary to have the same color.
This PR sets 'overlay' as the default and only switches the background to 'default' when displayed in the native app and in expanded mode.
before:
after:

fix(Audioplayer): background fix

---

apps/www/components/Article/ActionBarOverlay.js

before (actionbar invisible, behind audio player)
after
fixes:
https://www.notion.so/republikmagazin/12-Audio-player-over-floating-action-bar-in-article-8008aca33fb94e1fb6967855112a2c2d

fix(ACtionbar): correct audioplayer visibility handling

---

packages/styleguide/src/components/Figure/Slate.tsx
packages/styleguide/src/components/TeaserFront/SplitHeadline.js
packages/styleguide/src/templates/Front/index.js

– Smaller "Small" Headline for Split Image Tile on the Front
– Margin between Image and Ca

Layout fixes

---

apps/www/public/.well-known/assetlinks.json

Deep Links in Android stopped working. Google Play Store requested following changes to our assetlinks.json file, which verifies that our domain is associated with our app.
Needs to be deployed on love and

fix(Android): app verification assetlink file changes

---

apps/www/components/Front/index.js
packages/backend-modules/documents/lib/mdast/resolve.js
packages/styleguide/src/templates/Front/index.js

- fix(www/front): remove unused import
- feat(api): add has audio to urlMeta to be used in the front
- feat(www/front): render play button for all tiles with audio unless kind == 'syntheticReadAloud'
With these changes, the play button will be shown for all article-tiles that have an audioSource and the audioSourceKind !== 'syntheticReadAloud'.
(The problem was that the play-button wasn't shown for podcasts)

feat(www/front): show play-buttons on all tiles that have audio that isn't synthetic

---

apps/www/components/Audio/AudioPlayer/ui/tabs/shared/AudioCalloutMenu.tsx

Easy fix, just pass a Element that contains an IconButton. Same as in [Discussion/Internal/Comment/ActionsMenu](https://github.com/republik/plattform/blob/215bead5e8a9737988393ec7f01087929f915aeb/packages/styleguide/src/components/Discussion/Internal/Comment/ActionsMenu.tsx#L46) (where the [following item is passed](https://github.com/republik/plattform/blob/215bead5e8a9737988393ec7f01087929f915aeb/packages/styleguide/src/components/Discussion/Internal/Comment/ActionsMenu.tsx#L10))

fix(www/audio): render button to toggle AudioItem actions

---

packages/backend-modules/statistics/lib/matomo/collect.js
packages/backend-modules/statistics/lib/pgdb/redirections.js

matomo/collect did not check redirections table to find old paths
It now checks for previous paths and merges records

fix(statistics): find previous paths via redirections

---

apps/www/components/Audio/AudioProvider.tsx

With #276 I moved the active-playeritem state from the controller to the context. Due to that I renamed the previous activeItem (used in the legacy-player) to legacyPlayerItem. It seems I renamed it, instead of refactoring the variable-name. In combination with #277 this now causes the audio-player to close and lock the body after the last track is removed from the player.
This PR updates those references which caused the player to auto-close and lock the body-scroll

fix(www/audio): complete migrating variable ActivePlayerItem -> LegayPlayerItem introduced with #276

---

apps/www/components/Frame/Header.js

With #274 hasOverviewNav is not passed on the page component. In the Header however, the backbutton has previously only been rendered, if hasOvervierNav=false.
With this PR we attempt to regain the previous behaviour by generalizing the rule to render the back-button for logged-in users when ever a logged in user is in the iOSApp on a page other than the magazin-front

fix(www/nav): render the back-button in the iOS app on all pages but the magazin-front

---

packages/backend-modules/assets/lib/returnImage.js

Math.ceil rounds up, which could lead to a situation where the crop height would exceed the file size.
Using Math.floor fixes the issue. 
Example: Using the crop 0x18y100w82h on an image with the dimensions 2126x2661
it would try to extract:
top: Math.ceil((18 / 100) * 2126) = 478.9 => 479
height: Math.ceil((82 / 100) * 2126) = 2182.02 => 2183
479+2183 = 2662, which is 1 pixel higher than the image - > throws error
With Math.floor ensures that the crop is always lower than the total size.

fix(Assets): fixes rounding to round down on calculating crop size

---

apps/www/.env.example
apps/www/server/index.js

This Pull Request provides static files in `public/.well-known/` before redirect to `PUBLIC_BASE_URL` kicks in. A change necessar to accomodate domain validation ("republik.ch/.well-known/...", "www.republik.ch/.well-known/...", etc.).
It also redirects `/.well-known/webfinger` to URL provided in `MASTODON_BASE_URL`.

fix(www): redirect /webfinger, provide .well-known before redirect

---

apps/www/components/Article/Page.js
apps/www/components/Flyer/ActionBar.tsx
apps/www/components/Flyer/Footer.tsx
apps/www/components/Flyer/Meta.tsx
apps/www/components/Flyer/Nav.tsx
apps/www/components/Flyer/ShareImage.tsx
apps/www/components/Flyer/index.tsx
packages/styleguide/src/components/Typography/Flyer.tsx

- extract code from article page into `flyer/` folder
- split different components (e.g. flyer nav, flyer footer…) into different files
- add typescript
- reorder imports hierarchically
- types for `Typography/Flyer`
**No kitten should be harmed and no functionality should be affected by this refactoring**

www Journal Page refactoring

---

apps/publikator/components/Edit/Sync.js
apps/publikator/components/Publication/useValidation.js
apps/www/components/Flyer/Meta.tsx
apps/www/components/Flyer/index.tsx
apps/www/lib/translations.json
packages/styleguide/src/editor.ts
packages/styleguide/src/lib.ts

Sharing of individual journal blocks: when the block has a title, this becomes the title on social media, and we use a default sentence as description.
If the block doesn't have a title, we keep using the title and description set for the entire journal.

Journal: block title as metadata title

---

apps/www/components/Flyer/Meta.tsx

fix(Flyer): dimensions of shareimage tweak

---

apps/www/components/Notifications/SubscribedDocuments.js
apps/www/components/Notifications/enhancers.js
apps/www/components/Onboarding/Page.js
apps/www/components/Onboarding/Sections/Subscriptions.js
apps/www/components/Onboarding/Sections/Usability.js
packages/backend-modules/documents/graphql/schema-types.js
packages/backend-modules/search/lib/filters.js
packages/backend-modules/search/lib/indices/documents.js

This Pull Requests introduces `Meta.suggestSubscription`. It describes whether a section and its format is suggest by default to users.
It queries sections and formats as is, but now with `meta { suggestSubscription }` and filters for that flag.
In return, env variable `ONBOARDING_SECTIONS_REPO_IDS` is not longer needed.
It replaces https://github.com/republik/plattform/pull/299
Examples using "Journal":
/konto/benachrichtigungen
/einrichten
/rubriken
/suche
(section "In alle Kürze" won't appear since `feed` flag is disabled)
Pull Request includes [fix(search): drop match_all query in builders](https://github.com/republik/plattform/commit/d8436a5197a97b4e391a53e0d0ae93b40f258358): `match_all` as a fallback can cause unwanted side-effects if filter var is falsy
Release checklist:

feat: introduce Meta.suggestSubscription

---

packages/backend-modules/access/lib/mail.js
packages/backend-modules/mail/lib/scheduler/cleanedUserMailing.js
packages/backend-modules/mail/lib/scheduler/index.js
packages/backend-modules/mail/lib/sendMailsToSegment.js

This Pull Request upgrades codes which sends "re-opt-in" emails to ["cleaned MailChimp" users](https://github.com/republik/plattform/commit/88f93b8a8ee350c9df087f4bbc9c6812b20dcb5c) we saw falling of the list in the last 30 days (paused due to MailChimp outage).
It fixes [a faulty merge var](https://github.com/republik/plattform/commit/042702b6546f01b73de4edf0b543a04002e05412) for access grant transactionals – should have been a NOT check all along.
**Deployment Checklist**

fix: cleaned MailChimp user transactional, access grant transactional

---

apps/www/components/Front/index.js
apps/www/components/Overview/Page.js
apps/www/components/Overview/pages/2022.js
apps/www/components/Overview/pages/2023.js
apps/www/pages/2018.js
apps/www/pages/2018/index.js
apps/www/pages/2019.js
apps/www/pages/2019/index.js
apps/www/pages/2020.js
apps/www/pages/2020/index.js
apps/www/pages/2021.js
apps/www/pages/2021/index.js
apps/www/pages/2022.js
apps/www/pages/2022/index.js
apps/www/pages/2023.js
apps/www/pages/2023/index.js
apps/www/pages/2023/wochen.js

- add 2022 to known years
- add 2023 overview-page
- add 2023 overview-page to the Front loader archived years list.
- move year overview-pages into the corresponding year-folder for a less bloaty pages folder (the paths remain the same)
- For example: /2022.js -> /2022/index.js

feat: prepare carpet-text for 2023

---

apps/www/components/Climatelab/InlineTeaser/ClimateLabInlineTeaser.tsx
apps/www/lib/translations.json

Upon request from the art direction, the custom inline teaser gets replaced by a vanilla infobox with the climate lab logo.
Before:
Now:

fix(ClimateLab): implement amends to design of inline teaser

---

apps/www/lib/images/assetServerImageLoader.ts
packages/backend-modules/assets/lib/returnImage.js

- feat(assets): accept quality param to control the quality of the resized image (defaults to 80)
- feat(www): adapt AssetImage to correctly pass 'quality' to the assets-server

feat(assets): allow controlling quality of the resized images via the query-params

---

apps/www/lib/images/AssetImage.tsx

A oversight on my part while creating the asset-image.
As of now, images that are added to the static assets folder, can't be loaded by the AssetImage. (Once deployed to staging or production it works finde however.
With these changes, the AssetImage attempts to load images from the static assets folder directly with the next.js image-loader while in dev-mode.

refactor(www): enhance AssetsImage to load static files directly if in dev

---

packages/backend-modules/access/lib/grants.js
packages/backend-modules/access/lib/perks/accessWithRole.js

Added check if the user was already a member before the grant of the role by a perk, if so the member role is not removed with the end of the perk

fix: added check before removing member role granted by perks

---

packages/backend-modules/auth/graphql/resolvers/_queries/user.js
packages/backend-modules/auth/graphql/schema-types.js
packages/backend-modules/auth/graphql/schema.js
packages/backend-modules/auth/lib/AccessToken.js

This Pull Request allows users to issue an access token with scope `NOW_YOU_SEE_ME`. [See example query](http://localhost:5010/graphiql/?query=query%20getNowYouSeeMeToken%20%7B%0A%20%20me%20%7B%0A%20%20%20%20accessToken(scope%3A%20NOW_YOU_SEE_ME)%0A%20%20%7D%0A%7D%0A%0A&operationName=getNowYouSeeMeToken).
Token usable to query a few User props: `firstName`, `lastName`, `portrait`. [See example query](https://api.republik.love/graphiql/?query=query%20tallDarkStranger(%24accessToken%3A%20ID)%20%7B%0A%20%20user(accessToken%3A%20%24accessToken)%20%7B%0A%20%20%20%20id%0A%20%20%20%20email%0A%20%20%20%20portrait%0A%20%20%7D%0A%7D%0A&operationName=tallDarkStranger).
Token will expire after 30 days.
A token can either be issued by user itself or a user with superior roles like "admin" for another …

Add access token scope NOW_YOU_SEE_ME, query user w/ an access token

---

apps/www/components/Climatelab/Counter.js
apps/www/components/Climatelab/LandingPage/Page.tsx
apps/www/components/Climatelab/config.js

Add small numbers to climate lab counter, the small numbers are added through the props. There is an bool extended which hides the small numbers on the climate lab landing page.

Feat climatelab counter

---

packages/styleguide/package.json
packages/styleguide/src/components/Editor/Core/helpers/copy-paste.ts
packages/styleguide/src/components/Editor/Core/helpers/structure.ts
packages/styleguide/src/components/Editor/__docs__/flyer.md
packages/styleguide/src/components/Editor/test/copy-paste.test.js
yarn.lock

This PR improves the copy-paste behaviour in the journal in two ways:
The cursor needs to be placed into the same block as the first copied block for this to be triggered (e.g. if you want to copy topic + title into another tile, you should place the cursor inside the topic of the recipient tile).
https://user-images.githubusercontent.com/3907984/214612518-b38a9bd9-cffc-4343-baf9-b65b794966fc.mov
For instance, since there can be more than one paragraph, you could copy the title + topic from another tile, and paste those as paragraphs.
https://user-images.githubusercontent.com/3907984/214612451-f92d230b-5405-487c-897e-f2dae375279a.mov
For instance, the punchline can be a quote, hence quotes can be paste as-is in the punchline
https://user-images.githubusercontent.com/3907984/215451559-46fa0 …

Journal copy paste

---

packages/backend-modules/voting/graphql/schema-types.js
packages/backend-modules/voting/lib/Submission.js

We not can request the question of a specific user directly in the submission query.
`submissions(filters: {userIds: ["ca9c46ca-a21b-4f6e-aad3-1010acd419d5"]})`
[Like so.](http://localhost:5010/graphiql/?query=%7B%0A%20%20questionnaire(slug%3A%20%22sommer22%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20submissions(filters%3A%20%7BuserIds%3A%20%5B%22ca9c46ca-a21b-4f6e-aad3-1010acd419d5%22%5D%7D)%20%7B%0A%20%20%20%20%20%20totalCount%0A%20%20%20%20%20%20nodes%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20createdAt%0A%20%20%20%20%20%20%20%20updatedAt%0A%20%20%20%20%20%20%20%20displayAuthor%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20slug%0A%20%20%20%20%20%20%20%20%20%20profilePicture%0A%20%20%20%20%20%20%20%20%7D%0A%20 …

feat(Questionnaire): add userIds filter to submissions query

---

packages/backend-modules/mail/templates/future_campaign_sender_reward.html
packages/backend-modules/mail/templates/future_campaign_sender_reward.txt
packages/backend-modules/migrations/migrations/20230203150933-user-attributes.js
packages/backend-modules/republik-crowdfundings/graphql/resolvers/User.js
packages/backend-modules/republik-crowdfundings/graphql/schema-types.js
packages/backend-modules/republik-crowdfundings/lib/Mail.js
packages/backend-modules/republik-crowdfundings/lib/User.js
packages/backend-modules/republik-crowdfundings/lib/fiveYearsRewards.js
packages/backend-modules/republik-crowdfundings/lib/futureCampaignSenderReward.js
packages/backend-modules/republik-crowdfundings/lib/payments/Pledge.js
packages/backend-modules/republik-crowdfundings/package.json
packages/backend-modules/republik/migrations/sqls/20230203150933-user-attributes-down.sql
packages/backend-modules/republik/migrations/sqls/20230203150933-user-attributes-up.sql
packages/backend-modules/translate/translations.json
yarn.lock

This PR:
- adds new prop to `User` indicating how many mitstreiter slots (`futureCampaignAboSlots`) are used 
- adds a new method which is executed if certian utm_params are given in a payload of a pledge. this methods includes
- updating mitstreiter slot count
- fetching consent if sender wants to donate month
- if not donating: fetching current membership period and adding an extra month to this period
- sending an email with all these information to the sender
- adds mail template to be sent to sender accordingly 
- adds database migration to hold user attributes
TODO:

sender rewards for 5 years future campaign

---

apps/publikator/components/editor/modules/meta/ui.js
apps/publikator/lib/translations.json
apps/www/components/Access/Grants.js
apps/www/components/Account/belongingsQuery.js
apps/www/pages/dialog.js
packages/backend-modules/access/lib/memberships.js
packages/backend-modules/discussions/graphql/resolvers/Discussion/userCanComment.js
packages/backend-modules/discussions/graphql/resolvers/_mutations/downvoteComment.js
packages/backend-modules/discussions/graphql/resolvers/_mutations/editComment.js
packages/backend-modules/discussions/graphql/resolvers/_mutations/setDiscussionPreferences.js
packages/backend-modules/discussions/graphql/resolvers/_mutations/submitComment.js
packages/backend-modules/discussions/graphql/resolvers/_mutations/unpublishComment.js
packages/backend-modules/discussions/graphql/resolvers/_mutations/unvoteComment.js
packages/backend-modules/discussions/graphql/resolvers/_mutations/upvoteComment.js
packages/backend-modules/discussions/graphql/schema-types.js
packages/backend-modules/discussions/lib/Discussion.js
packages/backend-modules/discussions/lib/discussionPreferences.js
packages/backend-modules/discussions/lib/voteComment.js
packages/backend-modules/discussions/migrations/sqls/20230123153633-discussion-allowedRoles-down.sql
packages/backend-modules/discussions/migrations/sqls/20230123153633-discussion-allowedRoles-up.sql
packages/backend-modules/mail/script/generateClimateAccessGrants.js
packages/backend-modules/mail/templates/access_recipient_expired_klimalabor.html
packages/backend-modules/mail/templates/access_recipient_expired_klimalabor.txt
packages/backend-modules/mail/templates/access_recipient_onboarding_klimalabor.html
packages/backend-modules/mail/templates/access_recipient_onboarding_klimalabor.txt
packages/backend-modules/migrations/migrations/20230123153633-discussion-allowedRoles.js
packages/backend-modules/publikator/lib/Discussion.js
packages/backend-modules/translate/translations.json
packages/styleguide/src/templates/Article/index.js
packages/styleguide/src/templates/Discussion/index.js

This PR:
- adds option in meta section of publikator to open up discussion (article or discussion) for climate users
- adds handling of allowedRoles when document is published
- adds script to add new access grant to all climate users which handles expiring of trial
- changes edit and voting mutations on discussions so that users with specified roles are allowed to do these actions
- changes special handling for box on account page
Can be tested on love:
- if you subscribe now to Klimalabor you should only get `climate` role
- e.g. in this discusssion you should be able to comment, vote, ... https://www.republik.love/2023/01/31/mit-voller-kraft-gegen-die-klimakrise-diskutieren-sie-mit/diskussion and and here you should not be able: …

Discussion respecing allowed roles

---

apps/www/components/Search/Form.js

Fixes an issue where the search form didn't work when JS was disabled (because users have disabled it or when the script fails to load for some reason).

fix(Search): progressive enhancement of form

---

packages/styleguide/src/components/TeaserFront/ImageHeadline.js
packages/styleguide/src/components/TeaserFront/SplitHeadline.js
packages/styleguide/src/components/TeaserFront/TypoHeadline.js

Add top margins on some Front headlines, so they don't appear glued to the top of the box if there's no text above them.

fix(Front): headline margins

---

packages/backend-modules/discussions/graphql/resolvers/Discussion/userCanComment.js

This Pull Request revises `Discussion.userCanComment` prop.
It primarly checks if user has a role which is listed in `discussions.allowedRoles` (a). It wilfully ignores `member` role. `member` requires an additional check (b): user has to either have `debater` role or an active membership.
Revision fixes bug which allowed users with only `member` role to comment (without membership or `debater` role). Likely caused because array `DEFAULT_ROLES` was wrapped in array for filter (`![DEFAULT_ROLES].includes(role)`).

fix(discussions): check member role separatly

---

packages/backend-modules/search/lib/indices/questionnaireSubmissions.js
packages/backend-modules/search/lib/inserts/questionnairesubmission.js
packages/backend-modules/voting/graphql/schema-types.js
packages/backend-modules/voting/lib/Submission.js

This Pull Request allows querying for length of Text answers.
To achieve this, we populate and index `resolved.answers.resolved.value.length` with char length if question type is `Text`.
We then convert array with objects `resolved.answers` to [nested documents](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html) which gives us the power to query multiple props at once: `questionId` _and_ `length`.
Now, we need to extend our GraphQL schema with a filter interface:
```gql
input SubmissionsFilterInput {
...
answers: [
{ questionId: ID!, valueLength: { min: Int, max: Int } }
]
...
}
```
It will then query `questionId` and look for `valueLength.min` and  `valueLength.max`.

feat(voting): add filter to query value char length for Text questions

---

commitlint.config.js
package.json

It's 2023. All tools we use can do line breaks automatically. Even the Journal allows for 2500 characters. There's no reason not to do this. Please approve.

Increase commit line lengths

---

apps/www/components/Discussion/DiscussionComposer/DiscussionComposer.tsx
apps/www/components/Discussion/DiscussionComposer/DiscussionComposerBarrier.tsx
packages/backend-modules/discussions/graphql/resolvers/_mutations/editComment.js
packages/backend-modules/discussions/graphql/resolvers/_mutations/unpublishComment.js

Fixes permissions on comments so that logged in users can always edit or unpublish their own comments, no matter if they have a specific role.
Todo:

Fix permissions comment

---

apps/www/components/Climatelab/InlineTeaser/ClimateLabInlineTeaser.tsx

Add hideForMembers flag to, well, hide the inline teaser when reader is already a member.
Why? So we can embed the inline teaser on /klimalabor as well (some of the readers of this page might not be members already). Fyi: discussed with David.
Obligatory picture:

fix(ClimateLabInlineTeaser): add hideForMembers option

---

packages/backend-modules/migrations/migrations/20230316094520-drop-cash-payments.js
packages/backend-modules/republik/migrations/sqls/20230316094520-drop-cash-payments-down.sql
packages/backend-modules/republik/migrations/sqls/20230316094520-drop-cash-payments-up.sql

This Pull Requests drop table `cashPayments`.
Table is not in use anymore and data is available in `payments`, too.

chore(republik): drop table cashPayments

---

packages/backend-modules/republik/script/finance/calculateKpis.js

This Pull Requests extends script to calculate finance data with `YEARLY_ABO`.
Different to other products, we've to split pledge total into current fiscal year and transitory liabilities (aktuelles Geschäftsjahr und transitorische Passive).
We devide total amount to 365 parts. Amount of days left in fiscal year wander into `JahresabonnementsAktuellesGeschaeftsjahr` and rest wanders into `JahresabonnementsTransitorischePassive`.

Calculate finance data for YEARLY_ABO

---

apps/www/components/Sections/Featured.js

This Pull Request avoid an unhandeled error if `closeHandler` is not available.
Current implementation in www won't provide a `closeHandler` anymore which caused a uncaught error and reload of page.

fix(www): check if closeHandler is available

---

apps/www/components/Frame/Header.js
apps/www/components/Frame/Toggle.js

I accidentally introduced a bug with #412, that caused the nav-close and audio-toggle button to be rendered on top of each other.
This pr ensures that audio-toggle button is not visible when a nav is expanded (same as previous behavior)
https://user-images.githubusercontent.com/30313631/228080494-4edcbccc-1a10-4a49-a3d1-498893b15289.mov
https://user-images.githubusercontent.com/30313631/228080694-afb038a1-b4c6-4196-9445-785f55449c2b.mov

fix(www): nav-toggle regression

---

apps/www/components/Climatelab/EdgeQuestion/QuestionScroll.tsx
apps/www/lib/translations.json

In the Edge Question article of today, when clicking on a share link (e.g. https://www.republik.ch/2023/04/04/wir-koennen-eine-globale-katastrophe-abwenden?share=patrick-hofstetter) the header partially covers the person's answer. This PR mitigates the issue by adding an extra scroll-into-view step.
Bonus commit: adjust translations from 27'000 to 29'000 verlegerinnen. Whoot!

fix(EdgeQuestion): mitigate scroll issues for share links

---

apps/publikator/components/editor/MdastPage.js
packages/styleguide/src/lib.ts

Adds an ErrorBoundary to the main editor, and ensures that the user can still edit the raw source of an article in case the editor crashes.

Let Editor Crash More Gracefully

---

apps/www/components/Profile/Page.js
apps/www/components/Profile/graphql/useReportUserMutation.ts
apps/www/lib/translations.json
packages/backend-modules/republik/graphql/resolvers/_mutations/reportUser.js
packages/backend-modules/republik/graphql/schema.js
packages/backend-modules/republik/lib/slack.js
packages/backend-modules/translate/translations.json

Adds a report-user functionality. On a user profile next to the share-icon a flag-icon was added that prompts to enter a reason for reporting the user. When a user is reported, it is sent to the internal slack-channel, where previously only reported comments where shown.

feat: allow reporting user profiles

---

apps/publikator/components/Repo/Add.js
apps/publikator/components/Repo/Table.js
apps/publikator/components/editor/modules/meta/AudioForm.js
apps/publikator/pages/repo/[owner]/[repo]/raw.js
apps/www/components/ActionBar/Audio/Info.js
apps/www/components/Climatelab/Counter.js
apps/www/components/Events/Detail.js
apps/www/components/Search/Form.js
apps/www/pages/en.js
apps/www/pages/manifest.js
apps/www/pages/wahltindaer/[group]/[[...suffix]].js
packages/styleguide/src/components/Discussion/DiscussionCommentsWrapper.tsx
packages/styleguide/src/components/Figure/SwitchImage.js
packages/styleguide/src/components/TeaserFront/Split.js
packages/styleguide/src/components/TeaserFront/Text.js
packages/styleguide/src/components/TeaserFront/Tile.js

Since the React 18 upgrade, certain hydration errors lead to an actual error in dev mode. Production is not directly affected, since the errors will just be logged to the console but hydration mismatch leads to unnecessary re-rendering of the whole page. Let's fix that.
- I mainly checked all main pages of www and publikator, and had a quick look at admin (no issues there).
- Fixed all the critical hydration errors I could find, and some non-critical ones (e.g. style mismatches).
- I did fixed _some_ key warnings but not all of them. They are not critical at this point.
- There's a React key warning on front/TeaserMyMagazine that I can't seem to solve. All items do have unique keys but I still get the warning in the console.
- Probably best to review commit-by-commit

Fix Server-Client Hydration Errors

---

packages/backend-modules/assets/lib/returnImage.js
packages/backend-modules/assets/package.json
packages/backend-modules/documents/lib/common/meta.js
packages/backend-modules/publikator/lib/auphonic/index.ts

This Pull Request allows for a `bg` option to provide a default background color and replaces transparency (alpha channel) with decalred color. It further sets default audio cover background color to white.
Usage example:
http://localhost:5020/s3/republik-assets/repos/republik/format-am-gericht/images/d9d9981cc634153530bb57e0ccabc8d68cfbe726.png?resize=300x300&format=jpeg&bg=red

Allow optional bg query string to (audio cover) image URL

---

apps/admin/components/Users/Dialog/Credentials.js

If no credential was listed, filter failed [since `profileRole.id` was undefined](https://github.com/republik/plattform/compare/pae/fix-admin-credentials?expand=1#diff-7093a7ec393e1533dedcd0a574e05c4647bebbf3d8f415718febbaa8a2d23169L116).
Sort bubbles listed credentials to top if there are any.
Refactor to use guard clause.

fix(admin): avoid error if no credential is listed

---

packages/backend-modules/base/express/graphql.js
packages/backend-modules/base/package.json
yarn.lock

This Pull Request replaces deprecated `graphql-tools` package, getting `makeExecutableSchema` via successor package `@graphql-tools/schema`.

chore(base): replace package graphql-tools w/ @graphql-tools/schema

---

docs/next.config.mjs
packages/eslint-config-frontend/index.js
packages/eslint-config-frontend/package.json
yarn.lock

Seems with react-scripts being gone, we no longer need babel in the frontend eslint config 🥳

chore(eslint-config-fronten): update eslint setup to only use typescript eslint parser

---

apps/publikator/components/editor/modules/embed/index.js

Pasted Vimeo URLs with query params like https://vimeo.com/825451178?hey=ho&lets=go now also get properly converted to an embed in Publikator.

fix(publikator): accept vimeo urls with query params

---

packages/backend-modules/mail/templates/cf_comment_notification_new.html
packages/backend-modules/mail/templates/cf_comment_notification_new.txt

comments without a tag don't display a line for the tags in the email notification.
before:
after:
and with tag:

fix(email): do not display tags in the absence of tags

---

packages/mdast/remark-preset/src/span.js
packages/mdast/remark-preset/test/span.test.ts

(These changes are from a non merged pr in the remark-preset package in the mdast repo. [see #7 in orbiting/mdasst](https://github.com/orbiting/mdast/pull/7))

fix(mdast/remark-preset/span): harden data attribute value parsing

---

packages/backend-modules/republik-crowdfundings/lib/CustomPackages/index.js

All pledges and membership package options are taken into account for choosing a suggestedPrice at the moment, but only the latest pledge for your own membership should be used. Hence the filter by defaultAmount, which is greater than 0 for the right membership and package option (defaultAmount for gift memberships is 0).

fix: suggested price comes from correct pledge now

---

packages/backend-modules/auth/lib/AccessToken.js

When an access token of any type is resolved, it checks if the user has been deleted (for the cases where the user record has to be kept after deletion for administrative reasons).

fix(auth): check if user is deleted when resolving token

---

apps/www/components/CallToActions/BasicCallToAction.tsx
apps/www/components/CallToActions/CallToActionBanner.tsx
apps/www/components/CallToActions/CustomComponentBase.ts
apps/www/components/CallToActions/CustomComponentRegistry.ts
apps/www/components/CallToActions/customComponents/DatenschutzBanner.tsx
apps/www/components/CallToActions/graphql/CallToAction.ts
apps/www/components/CallToActions/graphql/useAcknowledgeCTAMutation.ts
apps/www/components/CallToActions/graphql/useCallToActionsQuery.ts
apps/www/components/CallToActions/useCallToAction.ts
packages/backend-modules/call-to-actions/graphql/resolvers/CallToActionPayload.js
packages/backend-modules/call-to-actions/graphql/schema-types.js

Adds a new type `CallToActionBasicPayload` to the cta API schema, for the most common use case of having text + link + linklabel.

Add Basic CTA

---

apps/admin/package.json
apps/www/package.json
package.json
packages/backend-modules/types/package.json
packages/backend-modules/utils/package.json
packages/icons/package.json
packages/mdast/mdast-react-render/package.json
packages/mdast/remark-preset/package.json
packages/mdast/slate-mdast-serializer/package.json
packages/nextjs-apollo-client/package.json
packages/styleguide/package.json
packages/tsconfig/nextjs.json
yarn.lock

- Define `moduleResolution` as [`nodenext`](https://www.typescriptlang.org/tsconfig#moduleResolution) (should be `bundler` but that's only supported by Next.js 13+), so the package.json `exports` field is correctly supported (instead of using `main`, `module` etc.).
- Upgrade TypeScript to v5
- Move the TypeScript dependency out of individual packages and into the root of the project (fewer moving parts and dependencies to manage)

TS Setup improvements

---

apps/www/components/Climatelab/Questionnaire/Overview.js
apps/www/components/Climatelab/Questionnaire/Person.js
apps/www/components/PoliticsCommunityQuestionnaire/Person.js
apps/www/components/Questionnaire/Submissions/AnswersGrid.tsx
apps/www/components/Questionnaire/Submissions/QuestionFeatured.js
apps/www/components/Questionnaire/Submissions/QuestionView.js
apps/www/components/Questionnaire/Submissions/graphql.js
apps/www/components/Questionnaire/Submissions/index.js

Adds a new query for fetching questionnaire submissions *without* questionnaire metadata.
This improves performance of the questionnaire overview significantly because at the time the submissions are fetched, questionnaire metadata has already been fetched and doesn't have to be re-fetched. Submissions for each question are queried separately which can lead to a lot of concurrent requests (this is still the case and should probably improved at some point). At least this way, each query takes ~1s whereas before it could take 5–10s.

Improve Questionnaire Overview Performance

---

apps/www/components/ColorScheme/ThemeProvider.tsx
apps/www/components/ColorScheme/useColorScheme.ts
apps/www/components/Frame/DarkmodeSwitch.js
packages/styleguide/src/components/Colors/ColorContext.tsx
packages/styleguide/src/templates/Front/index.js

- fix: force light theme on frontTileTeaser
- feat(styleguide): use data-theme instead of class for color-mode
- feat(www): communicate the color-scheme from nex-themes to the app
- feat(www): use data-theme attribute for styling & add migration util to migrate away from old color-scheme storage
- fix(styleguide): use data-theme to force color scheme in color context
- feat(www): update theme migration helper
- feat(www): useColorScheme now sets the theme via next-themes
- feat(www): get rid of useColorScheme usages

fix: theming issues

---

packages/backend-modules/documents/script/count.js
packages/backend-modules/republik/script/segment/defaultSegments.js

The document count script is used for our annual report and provides information about number of docs of a certain type, number of interactive stories and overall number of characters. 
In 22/23 we introduced the Republik Journal (and stopped it in the same financial year) and this minor change takes Republik Journal aka «flyer» into account as well.

Extend document count script

---

packages/backend-modules/republik-crowdfundings/graphql/resolvers/_mutations/reclaimPledge.js

Fixes the problem, that someone who reclaims the pledge (changes their email after buying a subscription, but before confirming the email) is not subscribed to onboarding emails with the updated email

fix subscribing to onboarding on reclaimPledge

---

packages/backend-modules/subscriptions/lib/Subscriptions.js

There was an error when trying to publish a document in Publikator, root cause has still to be checked, this is just a try to quick fix the issue.

fix(subscriptions): prevent error when object is undefined

---

apps/www/pages/api/prolitteris.ts

According to Kantar, this way tracking should work:
> Hallo Herr Baumann
>  
> Die späte Antwort tut mir leid, die Urlaubszeit auf allen Seiten hat leider nicht zur Beschleunigung der Thematik beigetragen.
>  
> Wir haben mit dem Betreiber des Zählsystem (Kantar) Rücksprache gehalten, das Zählsystem wertet die IP im Header nicht aus. Es gibt jedoch eine Alternative, die bereits im Einsatz ist.
> Bitte die IP nicht im Header „X-Forwared-For“ übertragen, sondern über den Parameter „i“ übertragen.
> Zum Beispiel: https://pl02.owen.prolitteris.ch/na/vzm.889053-republik-am-gericht-urteile-die-kein-mensch-mehr-versteht?c=12ce82b9f7ef0d432253&i=100.808.0.0
>  
> Viele Grüße
> Andreas Kohlweiß
> [Kantar Disclaimer](https://www.kantar.com/disclaimer)
> 
> 
> [Kantar …

fix(Prolitteris): fix tracking by adding i param

---

docs/tsconfig.json
packages/mdast/mdast-react-render/package.json
packages/mdast/remark-preset/package.json
packages/mdast/slate-mdast-serializer/package.json
packages/nextjs-apollo-client/package.json
packages/nextjs-apollo-client/tsconfig.json
yarn.lock

This PR bumps tsup to v7.2.0. Additionally the nextjs-apollo-client package is now also bundled with tsup. 🚀

chore: tsup-it-up

---

packages/styleguide/src/components/Chart/ChartContext.js
packages/styleguide/src/components/Chart/LineGroup.js
packages/styleguide/src/components/Chart/Lines.js

How to use:
you can add a strokeWidth to the json config of a line chart
```
strokeWidth: [6, 3]
``` 
The first value is the width used if a datum is highlighted, the second value is the normal / standard strokeWidth.

feat(Charts): add custom stroke width for line charts

---

packages/backend-modules/assets/express/frontend.js

When assets are loaded via CDN, the asset server tries to fetch the asset from the frontend first.
On parameterized routes, Next.js fetches URIs like `https://www.republik.ch/_next/static/chunks/pages/~/%5Bslug%5D-xyz.js`
The asset server decodes the special characters and tries to call `fetch("https://www.republik.ch/_next/static/chunks/pages/~/[slug]-xyz.js")` which seemed to work fine when fetching from Next.js 12 but Next.js 13 will return a 404.
When the asset URI is encoded, it works.

fix(assets): encode URI of frontend assets

---

apps/www/components/Marketing/Carousel.tsx

Fixes an error where the carousel ref could be undefined, possibly because it's used in a delayed callback.

fix(marketing): guard against missing carousel ref

---

packages/backend-modules/access/lib/memberships.js

This fix removes a query on access campaign type which has been executed while removing the member role. This caused an error because the type does not exist anymore and therefore invalidating of access grants stopped working.

fix(access): remove campaign type from removing member role

---

packages/backend-modules/mail/MailchimpInterface.js
packages/backend-modules/mail/lib/deleteEmail.js
packages/backend-modules/mail/lib/moveNewsletterSubscriptions.js
packages/backend-modules/republik-crowdfundings/graphql/resolvers/_mutations/deleteUser.js

- Delete user emails from all audiences on mailchimp when a user is deleted (deleteUser mutation)
- Update user email and interests/subscriptions on all audiences when a user email is changed

Handle mailchimp audiences correctly when users are deleted or change emails

---

apps/www/components/Questionnaire/ChoiceQuestion.js

We had an odd bug in a questionnaire instance
As seen in the video above, clicking the top checkbox in the third column
caused the wrong checkbox to be toggled.
After playing around with it, I noticed an issue with the area around the checkbox that allowed it to be toggled. Clicking the label yielded the expected outcome. (Video below)
The previous implementation seems to have been using some sort of a css-table(?).
I updated the layout to use CSS-Grid and it now seems to be working as expected.
(It should be note though that the order of the checkboxes has changed with the new implementation)

fix(www): convert choice-question layout to css-grid

---

apps/www/components/Questionnaire/Submissions/QuestionFeatured.js
apps/www/components/Questionnaire/Submissions/graphql.js

Instead dividing by the sum of all given answers, it should be divided by submissions.
This way, for multiple choice questions, they can add up to more than 100% (as they should)

fix(questionnaire): correctly calculate percentages in answers chart

---

apps/www/src/app/challenge-accepted/person/[slug]/components/person-bubble-graphic.tsx

After navigating back to the overview page, the positions of the force layout nodes were re-initialized incorrectly. By separating the person data from the layout data, we can track initialization properly, without relying on a ref.

Restart Challenge Accepted animation correctly

---

apps/www/components/Article/Page.js
apps/www/components/Audio/AudioPlayer/ui/tabs/latest/LatestArticles.tsx
apps/www/components/Audio/graphql/AudioQueueHooks.ts
apps/www/components/Audio/hooks/useAudioQueue.tsx
apps/www/components/Feed/DocumentListContainer.js
apps/www/components/Feed/index.js
apps/www/lib/errors/reportError.ts
apps/www/pages/[...path].tsx
packages/backend-modules/collections/graphql/schema-types.js

By default queries completely fail when a GraphQL error is encountered, this is a not-so-great experience in some cases because the whole section/page will fail to render, even when there is partial data available in the query response. By changing `errorPolicy` to `"all"` in those queries we'll have acces to data _and_ errors.
This should work fine in practice because in GraphQL, errors in subtrees remove the closest nullable field and leave the rest of the tree intact. E.g. when there's an error in the `Document.audioSource.durationMs` field, `Document.audioSource` will be null but the rest of the document is still available to render.
Additionally, this fixes a long-standing bug in the audio queue where unpublished documents would generate a GraphQL error if they're referenced in the …

Handle Certain GraphQL Errors More Gracefully

---

apps/publikator/components/Publication/useValidation.tsx

Switch to WHATWG URL for validating links in Publikator. This now can handle mailto-URLs (like `mailto:?subject=Hi`) without recipient properly (previously those were missing a `pathname` which caused a crash).
It would be nice to have unit tests for this but alas we don't ¯\_(ツ)_/¯

fix(publikator): improved link validation

---

packages/backend-modules/mail/MailchimpInterface.js

set count to fetch members from list to max (1000), because otherwise only 10 mails are fetched (and archived) every time the scheduler runs

fix archive unsubscribe on mailchimp

---

apps/www/server/index.js

This allows us to share URLs to protected deployments without users needing to go through the tedious step of navigating to the backdoor URL first. These will *both* work now:
- old: https://protected.republik.blah/secret-path → sets cookie and redirects to https://protected.republik.blah/
- new: https://protected.republik.blah/new-page?open_sesame=secret-path → sets cookie and redirects to https://protected.republik.blah/new-page (preserving pathname any extra search params)

feat: allow bypassing curtain message using a query param

---

packages/backend-modules/republik/graphql/resolvers/_mutations/updateMe.js

Updates the `updateMe` mutation to allow users with the `author` role to make their profile public.
This change should have been part of:
cefefcde1 (feat(auth): add author role, 2024-02-07)

fix(mutations/updateMe): allow users with author role to publish profile

---

packages/mdast/remark-preset/src/zone.js

This would cause a crash because parent is a readonly object. Instead we mutate the children in place.

Fix Publikator Crash for Articles with Embedded Comments

---

packages/backend-modules/referral-campaigns/lib/repo.ts
packages/backend-modules/republik-crowdfundings/lib/scheduler/index.js

Small fixes for campaign rewards scheduler to improve efficiency for future campaigns. 
- decrease scheduler frequency, now runs every 6h
- ignore non-personal referrals

Small fixes for campaign reward scheduler

---

packages/backend-modules/republik/script/gdpr/extractPersonalData.js

- adds the referral code and campaign referrals
- adds claimed referral rewards
- adds nl sign-up data from external sign-ups

chore(gdpr-export): add new datapoints to script

---

docker-compose.yml

Update the postgres version in the docke-compose to version 14.11 to match love and the upcoming production update.
The local postgres data directory needs to be deleted for this to work.

chore(dev): update postgres in docker-compose

---

package.json
scripts/heroku-cleanup.sh

Reduces heroku slug size from >400MB to ~270MB

chore: add heroku-cleanup

---

packages/backend-modules/republik-crowdfundings/lib/payments/stripe/createPaymentIntent.js
packages/backend-modules/republik-crowdfundings/lib/payments/stripe/createSubscription.js
packages/backend-modules/republik-crowdfundings/lib/payments/stripe/genIdempotencyKey.js
packages/backend-modules/republik-crowdfundings/lib/payments/stripe/payPledge.js
packages/backend-modules/republik-crowdfundings/lib/payments/stripe/paymentMethod.js

This is a bandaid for the existing payment flow.
A payment with the same pledgeId and the same payment method should always return the same payment Intent for 24 hours.
- The idempotent key is derived from the pledgeId and the payment method id

Use Idempotent key to prevent double pay

---

apps/assets/package.json
apps/assets/server.js
packages/backend-modules/base/__tests__/corsRegex.u.jest.js
packages/backend-modules/base/lib/corsRegex.js
packages/backend-modules/base/package.json
packages/backend-modules/base/server.js
yarn.lock

Turns every domain in the CORS_ALLOWLIST_URL to a regex pattern, escaping `[.*+?^${}()|[\]\\]` and turning `*` into `\.*`.
== Examples ==
```
https://www.republik.ch => /^https:\\/\\/www\\.republik\\.ch$/
https://*.republik.ch => /^https:\\/\\/.*\\.republik\\.ch$/
```

feat(cors): translate allow list to regex patterns

---

packages/backend-modules/base/__tests__/corsRegex.u.jest.js
packages/backend-modules/base/lib/corsRegex.js

the new dynamic regex matcher prevents request proxied from localhost.
There is no real reason why we should prevent localhost request similar to requests cli tools like `curl`

feat(cors): always allow request from localhost

---

apps/api/README.md
docker-compose-test.yml
docker-compose.yml

Adds [MailHog](https://github.com/mailhog/MailHog) to the docker compose for local transactional email testing with the node SMTP mailer.
To make the SMTP mailer work add the following vars to your .env
```
SEND_MAILS=true
SEND_MAILS_TAGS=dev
SEND_MAILS_REGEX_FILTERS=^([a-zA-Z0-9\._%+-]+)@republik\.(ch|test)$ // to allow *@republik.ch or *republik.test
SEND_MAILS_NODEMAILER_TEMPLATE_REGEX='^.+'
SEND_MAILS_NODEMAILER_CONNECTION_URL='smtp://user:password@127.0.0.1:1025'
SEND_MAILS_SUBJECT_PREFIX='Test Local'
```

feat(docker): add mailhog container

---

packages/backend-modules/mail/templates/signin.html

Inserts links as raw string to prevent double encoding of links

fix(signin): insert login link as raw string

---

packages/backend-modules/base/express/graphql.js

The default cache config of apollo server can be used for DOS attacks

chore(base/graphql): set apollo server cache to bounded

---

apps/www/lib/utils/conversion-payload.js
apps/www/pages/_app.tsx
apps/www/src/app/layout.tsx
apps/www/src/lib/analytics/utm-session-storage.tsx

Stores UTM params in session storage to prevent them getting lost on the way to the final checkout page.
This is inspired the old implementation removed in #884 but uses sessionStorage instead of localStorage and doesn't track the path of the user.

UTM Session Storage

---

apps/project-r/README.md
apps/project-r/src/Footer.js

This PR adds our newest Vorstand member to the footer.
As the `README.md` of the `project-r` app had outdated instructions, this PR also attempts to improve that.

Update to Vorstand List

---

apps/www/components/StatusError/index.js

Sometimes, `history.back()` doesn't do anything (e.g. when the app is loaded fresh), so users can get stuck on the redirection page.

fix: redirect back to home after a redirect in the app

---

apps/publikator/components/Publication/useValidation.tsx
packages/styleguide/src/templates/shared/audio.js

1. Display more prominently the issue when no voice is selected upon publishing.
2. Add play button for synthetic voice on front tiles

Huebsch release fixes

---

apps/publikator/components/Derivatives/index.js
apps/publikator/components/Publication/Current.js
apps/publikator/components/Publication/PublicationForm.js
apps/publikator/lib/translations.json
apps/publikator/next-env.d.ts
apps/publikator/pages/repo/[owner]/[repo]/tree.js
apps/www/next-env.d.ts
packages/backend-modules/migrations/migrations/20241002113441-commits-with-readaloud.js
packages/backend-modules/publikator/.gitignore
packages/backend-modules/publikator/graphql/resolvers/Commit.js
packages/backend-modules/publikator/graphql/resolvers/Derivative.js
packages/backend-modules/publikator/graphql/resolvers/_mutations/generateDerivative.js
packages/backend-modules/publikator/graphql/resolvers/_mutations/publish.js
packages/backend-modules/publikator/graphql/schema-types.js
packages/backend-modules/publikator/lib/Derivative/SyntheticReadAloud.ts
packages/backend-modules/publikator/lib/Derivative/associateReadAloudDerivativeWithCommit.ts
packages/backend-modules/publikator/lib/types.js
packages/backend-modules/publikator/lib/types.ts
packages/backend-modules/publikator/loaders/Commit.ts
packages/backend-modules/publikator/loaders/Derivative.ts
packages/backend-modules/publikator/migrations/sqls/20241002113441-commits-with-readaloud-down.sql
packages/backend-modules/publikator/migrations/sqls/20241002113441-commits-with-readaloud-up.sql
packages/backend-modules/publikator/script/copyImages.ts

add feature to skip audio generation while publishing, and use audio from latest published commit instead. Adds new table to associate derivatives with commits.

fix(SyntheticReadAloud): associate derivatives with commits so that not every publish or commit needs a newly generated audio if not necessary

---

packages/backend-modules/republik/graphql/resolvers/User.js
packages/backend-modules/republik/graphql/resolvers/_mutations/updateMe.js
packages/backend-modules/republik/lib/profile.js

Check `hasUserActiveMembership` instead of membership table for profile eligibility. 
Alternative implementation: we could also replace `isEligible` directly with `hasUserActiveMembership`.

fix(profile): make people with subscriptions eligible for public profile

---

packages/backend-modules/republik/lib/MembershipStats/evolution.js
packages/backend-modules/republik/lib/MembershipStats/lastSeen.js

Correct data for charts on [cockpit](https://www.republik.ch/cockpit) so that new members with subscriptions are correctly shown. 
Relevant data:
- active subscribers
- new subscriptions, ended subscriptions
- subscribers active on the site
- discussions: doesn't depend on membership type

Include new subscriptions in cockpit query

---

apps/www/middleware.ts

Problem:
```
useEffect(() => {
if (meLoading) return
// reload to re-trigger the middleware to rewrite to the marketing-page
if (!hasAccess) {
window.location.reload()
}
}, [meLoading, hasAccess])
```
`pages/index.tsx`: the marketing redirect never takes effect, which cause the page to reload and reload and reload…
(Tentative) fix: always call `rewriteBasedOnMe` in the middleware. Why did the session cookie disappear? No idea. 
1. Please test thoroughly before merging. 
2. Maybe returning that session cookie is a better fix?

fix(Front): fix infinite loop on the front

---

packages/backend-modules/republik/script/finance/calculateKpis.js

The subscriptions should be included with the memberships and abonnements, and marked as reduced if a coupon was applied. Hence there are no new fields for PROJECT_R,  because they are included with ReduzierteMitgliedschaften, but new fields for REPUBLIK, for ReduzierteAbonnements and StornierteReduzierteAbonnements. The payment method is still Stripe, but might change when we start using Stripe with Paypal/Twint, depending on how the booking is organised between stripe and external payment providers.

chore(calculateKpis): adapt to subscriptions

---

apps/publikator/components/editor/modules/document/createPasteHtml.js
apps/publikator/components/editor/utils/keyHandlers.js

Consecutive newlines in the title block are the ex-aequo number one cause of editor bugs in publikator (together with scrambled memos), as markdown interprets two consecutive `\n\n` as a new paragraph. However, multiple titles, or leads, are not tolerated.
This PR adds two new behaviours:
1. Ignore every newline insert that follows or precedes another newline character (`\n`)
2. Collapse multiple consecutive newlines into a single newline on copy-paste. An exception is made for paragraph types, where multiple newlines are converted into a double newline, which leads to the creation of a new paragraph (desired behaviour for paragraph types)

fix(editorCore): forbid consecutive newline inserts

---

apps/www/components/Article/ActionBarOverlay.js
apps/www/components/Audio/AudioPlayer/AudioPlayer.tsx
apps/www/components/Audio/AudioPlayer/ExpandedAudioPlayer.tsx
apps/www/components/Audio/AudioPlayer/ui/tabs/shared/AudioCalloutMenu.tsx
apps/www/components/Frame/BottomPanel.js
apps/www/components/Frame/DarkmodeSwitch.js
apps/www/pages/_app.tsx
packages/styleguide/src/components/Callout/CalloutMenu.tsx
packages/styleguide/src/components/Callout/docs.md
packages/styleguide/src/components/Callout/index.tsx
packages/styleguide/src/components/Discussion/Internal/Comment/ActionsMenu.tsx

This PR fixes `env(safe-area-inset-...)` not working properly. It wasn't working in the webview of our react native app, because `viewport-fit=cover'` wasn't set on the meta tag.
Now that it's set it is working as expected and the Callout Element has been simplified by removing the explicit definition of mobile paddings. Now it defines consistent paddings that work both in Native and Web views
example web:
same code in native (notice that the marginBottom is larger, because the bottom margin is added to the safe area start `calc(15px + env(safe-area-inset-bottom))`. This ensures consistent hit boxes and enough space that the native UI elements and our buttons don't conflict:
before the change, the last item of the list was very close to the bottom UI
using env(safe-are-inset..) ensures …

fix: consistent audio player offset & env(safe-area-) fixes

---

apps/publikator/components/editor/modules/embeddatawrapper/EditOverlay.js
packages/styleguide/src/components/Datawrapper/index.tsx
packages/styleguide/src/components/Figure/index.tsx

- Removed the alt field, as it's not necessary. Alt texts are already part of DW charts (if the author sets them)
- Added a setting to force dark mode. Not optimal but the only way I can think of to make them work in forced dark mode articles
- Some improvements (hopefully) around error handling when chart metadata could not be loaded etc.

Datawrapper 1st Improvements

---

apps/publikator/components/editor/modules/document/createPasteHtml.js

Inserting the **text** manually for slate-to-slate copy-paste is removing all the styling/links/etc.
We leave slate to handle these inserts and only check/edit text and html copy-pastes

feat(coreEditor): fix disappearing links upon copy paste

---

packages/styleguide/src/components/Discussion/Internal/Comment/Header.js

fix: missing flexshrink distorts profile images in comments on mobile

---

packages/styleguide/src/components/InfoBox/Subhead.tsx
packages/styleguide/src/components/List/List.tsx

Due to the global reset.css which sets margin: 0 in the frontend, List and Subhead components need explicit definitions of margins, since before they relied on browser defaults (usually 1em). 
With these margins added back, the negative margins that were removed as a quick fix can be added back, resulting in visual parity between publikator and www.

fix: infobox margins

---

apps/publikator/components/editor/MdastPage.js
packages/styleguide/src/components/Chart/ScatterPlots.js

`sort` sorts the array in place, which caused a bug in our scatter plots.
https://stackoverflow.com/questions/53420055/error-while-sorting-array-of-objects-cannot-assign-to-read-only-property-2-of

Fix scatter plot

---

packages/styleguide/src/components/Typography/Editorial.tsx
packages/styleguide/src/templates/Article/base.js
packages/styleguide/src/templates/Article/blocks.js

Replace wrapping `div` around interview-answer `p` with a `no-top-margin` class, in the hope it fixes our pdf problem.

fix(InterviewAnswer): replace wrapping div with css class

---

apps/www/components/Profile/ProfileView/ProfileUrls.tsx

If users had invalid urls stored (could be during migration or an edge case that is not caught with the url validator) the site crashes. The regex typeerror should never crash the site but fallback gracefully to a default value

fix: harden regex with try catch

---

apps/www/components/Account/Memberships/Manage.js
apps/www/components/Frame/ProlongBox.js
apps/www/pages/teilen.js

~~apps/www/components/Account/Memberships/Manage.js~~
~~Users with yearly abo and monthly abo are now directed to shop when they click on "Jahresmitgliedschaft kaufen" button~~ *needs to stay with ABO since we can't upsell new packages yet
apps/www/components/Frame/ProlongBox.js
The Prolongbox links to the new shop if the membership that is expiring can't be prolonged (yearly_abo for example) !membership.canProlong
apps/www/pages/teilen.js
The hard coded paynote on the teilen page now links to the new shop overview for both monthly and yearly

chore: remove links to package ABO to force redirect to new shop

---

.husky/commit-msg
.husky/pre-commit
commitlint.config.js
package.json
yarn.lock

Removing the commitizen/commitlint/husky/lint-staged pre-commit hooks since we all agree that running `eslint --fix` when you want to commit has been 0 times useful and several times annoying, as it will always fail on some random old file.
Also the configuration seemed weird to me, as far as I understand: if husky is installed, we wouldn't need commitizen but I didn't look into it too much. I removed everything because it doesn't feel particularly useful to us anymore and if we need something like this in the future, we'll just add it back.

Remove Pre-Commit Hooks

---

packages/backend-modules/utils/hasUserActiveMembership.js

Fixes the hasUserActiveMembership check to exclude subscriptions in the incomplete_expired state.
Subscriptions that are incomplete change to the incomplete_expired state after 24 hours.

fix: filter out incomplete_expired in hasUserActiveMembership

---

packages/backend-modules/republik-crowdfundings/lib/scheduler/owners.js

The result of the `getMinEndDate` function should not have a real effect considering that this job is run every 10 minutes.
Unless someone edited a membership in the database directly, there should never be a case where a `YEARLY_ABO` is 3 days past due and has not received this mail. The behaviour is left in place to cover these edge cases.
Since the new shop only allows purchasing a new subscription if there is no active membership, the `maxEndDate` has been set to the time when this job is run to prevent users from receiving this email before their membership runs out.

fix(scheduler): limit the time reange for the yearly prolong mail

---

packages/backend-modules/migrations/migrations/20250317141543-update-refresh-member-role.js
packages/backend-modules/payments/lib/handlers/stripe/subscriptionDeleted.ts
packages/backend-modules/payments/lib/payments.ts
packages/backend-modules/payments/migrations/sql/20250317141543-update-refresh-member-role-down.sql
packages/backend-modules/payments/migrations/sql/20250317141543-update-refresh-member-role-up.sql

updates the refresh_member_role postgres function to check for the existence of a active subscription to determine if it should remove the `member` role

fix: update refresh_member_role to check for subscriptions

---

packages/backend-modules/mail/fonts.js
packages/backend-modules/mail/templates/membership_owner_prolong_yearly_abo_winback_16.html
packages/backend-modules/mail/templates/membership_owner_prolong_yearly_abo_winback_24.html

Noticed some logs from the asset server about these urls, so I fixed them.

fix(mail): use correct rubis font urls for mails

---

packages/backend-modules/base/express/graphql.js
packages/backend-modules/base/server.js

- Don't log errors in `formatError` – that's not what it's intended for 😓 
- Use a ApolloServer plugin for logging, which has access to the request context (and thus, the `req._log()` function)
- Remove `debug: true` and thus the need to delete the exception from the client response. This way, it's [automatically omitted in production](https://www.apollographql.com/docs/apollo-server/v3/data/errors#omitting-or-including-stacktrace)

feat(backend): improve gql error logging

---

apps/www/components/Article/useSchema.tsx

some unnecessary dependencies trigger the regeneration of the schema. they are replaced by references. now the schema is generated only one.

render schema only once

---

apps/publikator/components/editor/MdastPage.js

A quick and dirty fix for when a document cannot be parsed/serialized during a commit. The existing code would only catch GraphQL errors.
Instead of showing the spinner indefinitely, this is now displayed like other errors:
The real solution is to avoid transforming back-and-forth between Markdown and MDAST, like in #963

fix(publikator): catch parse/serialize error when committing document

---

apps/www/components/Account/Memberships/index.js

Shows a link to shop only in iOS Apps with version 2.3 or higher.

add external-link to account page

---

apps/www/src/components/paynotes/regwall/index.tsx
apps/www/src/lib/analytics/provider.tsx

We were sending the metering cohort in the analytics provider, which caused only techincal issues, as i suspect the provider would read the values before the window object and localstorage were defined. also if the metering object was created once the provider already existed, this update wouldn't propagate to the provider without some changes to the code.
**As a fix:** we only send the metering cohort where it's relevant, aka as data for the regwall events.

only send metering status for regwall events

---

apps/www/src/components/paynotes/paynotes-context.tsx

Currently the metering is checked before the trial status. Leading to an effect that on articles where reading is granted the paywall doesn't show up. This could be revered to show a more consistent experience, where after the trial ends the paywall always appears.

prioritise trial status for paywall instead of metering

---

apps/www/components/ActionBar/index.js
apps/www/components/Audio/AudioPlayer/ArticleAudioPlayer.tsx
apps/www/components/Audio/AudioPlayer/MiniAudioPlayer.tsx
apps/www/components/Front/index.js
apps/www/lib/context/MeContext.tsx

for non-members:
- remove play/audio queue buttons from feed
- remove audio queue button from article audio element (anonymous users don't have an audio queue)
- remove expand button from audio player (it expands into the queue manager, which doesn't make sense here)
bonus fix:
- remove clunky `canReadFreely` function and use better `isMember` attribute on `me`.

remove audio buttons for non-members when they don't make sense

---

apps/www/public/robots.txt

Tries to make the robot.txt file more coherent by disallowing all training and allowing indexing for search by AI search engines and models to provide users with links to our content in those platforms.
**Disallows**
- [Meta-ExternalAgent](https://developers.facebook.com/docs/sharing/webmasters/web-crawlers/), meta's bot for trainig
- A bunch of AI crawlers from: https://github.com/ai-robots-txt/ai.robots.txt/blob/main/robots.txt
**Allows**
- Applebot: Apples search bot. [Only Applebot-Extended is used to train models](https://support.apple.com/en-us/119829):
- ChatGPT-User:  [Not used for training](https://platform.openai.com/docs/bots) but for delivering results from within ChatGPT.
- Claude-Web and Claude-User:[Used for web results in …

disallow meta training bot, allow ai search bots and user bots

---

apps/www/components/Notifications/SubscribedAuthors.js
apps/www/components/Notifications/enhancers.js
apps/www/components/Onboarding/Page.js

Previously the employees were fetched from the gsheets table to show the above the "normal" users. This is not possible anymore. Instead of doing some complex merge of datocms data and user data, I opted to just render the list of subscribed users alphabetically and do aways with the distinction. Since we're tackling authors next, this should be an acceptable solution until we have a more robust author follow feature.

fix employees being fetched for following authors/users

---

packages/backend-modules/statistics/script/analyzeCredits.js

Add option `text-only` to gender script. When switched on, this option filters out any roles which aren't `Text`

add text only option to gender script

---

apps/www/components/Feed/index.js

Querying the greeting generates API errors for users that are not logged in. Additionally, using a GraphQL subscription here seems very wasteful, since the content never observably changes.

fix(www): remove greeting from feed

---

apps/api/server.js
apps/api/workers/cockpit.js
apps/www/pages/cockpit.js
packages/backend-modules/collections/graphql/resolvers/CollectionsStats/evolution.js
packages/backend-modules/discussions/graphql/resolvers/DiscussionsStats/evolution.js
packages/backend-modules/migrations/migrations/20250604102839-cockpit-materialized-view.js
packages/backend-modules/republik/graphql/resolvers/MembershipStats/evolution.js
packages/backend-modules/republik/graphql/resolvers/MembershipStats/lastSeen.js
packages/backend-modules/republik/lib/MembershipStats/evolution.js
packages/backend-modules/republik/migrations/sqls/20250604102839-cockpit-materialized-view-down.sql
packages/backend-modules/republik/migrations/sqls/20250604102839-cockpit-materialized-view-up.sql

Updates the resolvers used by the `/cockpit` page to fetch the data from materialised views instead of the Redis cache.
- Main benefit is that the data is no longer being evicted from the cache preventing the cockpit form breaking randomly.
- The views can also be used in our metabase queries.
The current cockpit on staging fetches the data from materialised views already
- removal of the populate scripts for the redis cache
- removal of unused resolvers.

Use materialised views for cockpit cache

---

apps/www/package.json
apps/www/src/app/api/(sitemaps)/[year]/news-sitemap/route.ts
apps/www/src/app/sitemap.xml/route.ts
yarn.lock

Two news-sitemaps were failing because they add the title of an article to the sitemap, not just the path. And in rare cases, we had characters in the titles that should be be escaped for XML. For example: & should be &amp;
I added back the jstoxml library I had removed, which escapes all necessary characters.
Also sets the START_YEAR to 2018, since we didn't publish in 2017.

fix news sitemap

---

packages/backend-modules/collections/migrations/sqls/20250616113324-add-collection-items-created-at-index-down.sql
packages/backend-modules/collections/migrations/sqls/20250616113324-add-collection-items-created-at-index-up.sql
packages/backend-modules/migrations/migrations/20250616113324-add-collection-items-created-at-index.js

In most of our analytics queries for the collectionDocumentItems we sort the data by date, the query planner showed that most of the time is spent on sorting the entries. Adding an index for the common sort should drastically improve performance.

add "createdAt" desc index to collectionDocumentItems

---

packages/backend-modules/republik/graphql/resolvers/User.js

We should never expose any sensitive fields to the public if the user decided to set their profile to private.

check if profile is public before all other checks

---

apps/publikator/components/VersionControl/index.js
apps/publikator/components/editor/MdastPage.js

I accidentally removed the character count from the workflow tab because i couldn't imagine why you'd need it on both tabs. Turns out you do because if someone else is in the doc, you can't see the edit tab.

add back characterCount to workflow tab

---

apps/www/src/app/api/email-open/route.ts
packages/backend-modules/publikator/graphql/resolvers/_mutations/publish.js

1. Doesn't inject the image into the mailchimp html on publishing a newsletter
2. Only returns the image o the email-open route, without sending the request to plausible. We do this because if we return nothing, email clients will complain that the email content couldn't be loaded properly. We can remove this route in the future, when it's unlikely that older emails are being openend anymore.

remove email plausible tracking

---

apps/www/components/Discussion/hooks/actions/useSubmitCommentHandler.ts

In some cases, updating the cache after a comment submission doesn't work because the cache is empty. Then, we just do nothing.
Also updates to the more recent [`cache.updateQuery`](https://www.apollographql.com/docs/react/caching/cache-interaction#using-updatequery-and-updatefragment) instead of using `readQuery` and `writeQuery`.

Fix Comment Submissions

---

apps/www/components/Audio/AudioPlayer/ui/tabs/shared/AudioListItem.tsx
apps/www/components/Audio/hooks/useMediaProgressQuery.ts

Progress is already queried in the initial audio queue query, so we DON'T NEED TO DO IT AGAIN FOR EACH INDIVIDUAL QUEUE ENTRY!

Fix AudioQueue Overfetching

---

packages/backend-modules/discussions/lib/discussionPreferences.js

Fixes a bug that would deanonymize users when they change their discussion notficiation preferences.

preserve user settings on anonymity in dialog

---

apps/www/components/Frame/Header.js
apps/www/src/components/layout/pull-to-refresh/index.tsx

We had to disable the bodylock feature on the expanded audio player since it stopped the queue scrolling from working. This hoever introduced the isse that when you were at the top of an article page and scrolled up on the queue, it would triger a page reload. this pr checkes disables pull to refresh in the app and pages folder, if the audioplayer is in its expanded mode. 
Tested in simulator with local frontend.

fixes pulltorefresh bodylock issue

---

apps/www/src/app/(campaign)/components/campaign-offers.tsx
apps/www/src/components/paynotes/campaign-paynote/campaign-overlay.tsx
apps/www/src/components/paynotes/paynotes-context.tsx

Fixes an issue where the Regwall would show up if the user was assigned a trial status already. Bonus: the campaign-related paynote logic should be easier to understand now :)
Also:
- Fixes wrong offer highlight color in dark mode on the campaign page
- Removes some unnecessary paynote data loading and event tracking data (there's only 1 variant for the campaign and no relevant trial/metering data)

Campaign fixes

---

apps/www/components/ActionBar/UserProgress.js
apps/www/components/Article/Progress/index.js

Occasionally `upsertDocumentProgress` would be called with an undefined `documentId`, which isn't allowed by the schema.

Fix upsertDocumentProgress

---

apps/publikator/components/Files/index.js
apps/publikator/components/editor/enhancers.js
apps/publikator/lib/translations.json
apps/publikator/pages/repo/[owner]/[repo]/files.js
apps/publikator/pages/repo/[owner]/[repo]/tree.js
packages/backend-modules/publikator/graphql/resolvers/_queries/repo.js
packages/backend-modules/publikator/graphql/schema.js

A repo query for a non-existent repo should return null instead of throwing an error. This fixes excessive error logging when Publikator polls for uncommited changes on a repo that hasn't been created yet.

Make repo resolver nullable
