apps/api/dev.js
apps/api/package.json

This Pull Request will run api server and scheduler for development.

chore(api): run server, scheduler at once in development

---

apps/www/components/Footer/index.js

So we don't forget to change the link to our repo in the frontend.

fix(www-Footer): add new github link to frontend

---

apps/www/components/Profile/Portrait.js

https://github.com/orbiting/republik-frontend/issues/679
before
after

fix(Portrait): darkmode compatibility for drop area

---

apps/www/components/Frame/Popover/Nav.js

closes #8 
@patrickvenetz - couldn't test because my backend is whack. Could you test to see if behavior is as expected now?

fix(Nav): only show search field if has activeMembership

---

apps/publikator/components/PreviewFrame/index.js
apps/publikator/components/Publication/HasAccessToggle.js
apps/publikator/components/Publication/index.js
apps/publikator/pages/repo/preview.js

Preview a document as user without restrictions (default) or without logged in.

feat(publikator): toggle logged in user in preview

---

apps/www/components/Notifications/NotificationFeedMini.js
apps/www/components/Notifications/enhancers.js

Redirect notifications to external url when applicable

fix(Notification): support for external base url

---

packages/backend-modules/documents/graphql/resolvers/Document.js
packages/backend-modules/documents/lib/__snapshots__/process.u.jest.js.snap
packages/backend-modules/documents/lib/process.js
packages/backend-modules/documents/lib/process.u.jest.js
packages/backend-modules/testing/package.json

Fixed version of https://github.com/republik/plattform/pull/56 which lacked visting [index reset](https://github.com/republik/plattform/compare/feat-process-if-hasaccess?expand=1#diff-6255b896868c29edb4af46f3b53c53247b80b691f644c8b8707bc540e4b2396cR188-R189)

feat(documents): process IF hasAccess in document.content

---

apps/www/lib/translations.json

fix(Marketing): new copy for kolumnen

---

apps/www/components/Article/ReadAloudInline.tsx
apps/www/lib/translations.json

feat(ReadAloudInline): smaller version

---

packages/styleguide/src/components/Chart/Table.docs.md
packages/styleguide/src/components/Chart/Table.js

This PR adds a bar chart feature to the table.

feat(Table): add bar chart option

---

apps/publikator/components/editor/modules/teaser/ui.js
apps/publikator/components/editor/utils/ColorPicker.js
apps/publikator/lib/translations.json

fix(A11Y): draft contrast info

---

apps/www/components/Questionnaire/Submissions/index.js
apps/www/components/Search/Sort.js
apps/www/lib/translations.json

add sorting and fix some minor search field stuf
f

Quest for more summer

---

apps/www/components/Frame/Popover/index.js
apps/www/components/Questionnaire/Submissions/Share.js
apps/www/components/Questionnaire/Submissions/Submission.js
apps/www/components/Questionnaire/Submissions/index.js
apps/www/components/Search/Form.js

Put question into summer share image if it and the answer is not too long
Also small improvements for the general navi and search reset accessibility.

Final Summer

---

yarn.lock

build(yarn): recreate lock file

---

apps/admin/package.json
apps/www/lib/helpers/middleware/FetchMeObject.ts
apps/www/package.json
packages/nextjs-apollo-client/package.json
yarn.lock

Bump Next.js to v12.2.4 and refactor the API-Call, that is made to the api to retrieve me.roles + the user-token, to be a GET-request.

Bump Next.js to v12.2.4 and refactor middleware me.roles fetching

---

apps/www/components/Article/metadata.js
apps/www/components/Frame/Meta.js

Adds the following meta-tags, based on the [Zotero documentation](https://www.zotero.org/support/dev/exposing_metadata):
- citation_title
- citation_journal_title
- citation_date
- citation_authors

feat(www): add citation meta tags for zotero

---

apps/www/components/ActionBar/index.js
apps/www/components/Feed/Feed.js
packages/styleguide/src/components/TeaserFeed/index.js

fix(Feed): don't render actionbar on newsletter and flyer

---

packages/styleguide/src/components/Editor/config/elements/list/container.tsx
packages/styleguide/src/components/Editor/config/elements/list/item.ts
packages/styleguide/src/components/Editor/schema/flyer.tsx
packages/styleguide/src/components/Editor/test/block-conversion.test.js
packages/styleguide/src/components/Editor/test/block-insertion.test.js
packages/styleguide/src/components/Editor/test/navigation.test.js
packages/styleguide/src/components/Typography/Flyer.tsx

https://user-images.githubusercontent.com/3907984/193584850-341e3a48-b5cd-46af-b876-e2615995b670.mov

Journal List Design Amends

---

apps/www/components/Audio/AudioPlayer/MiniAudioPlayer.tsx
apps/www/components/Audio/AudioPlayer/ui/AudioCover.tsx
apps/www/components/Audio/AudioPlayer/ui/CurrentlyPlaying.tsx
apps/www/components/Audio/AudioPlayer/ui/tabs/shared/AudioListItem.tsx
apps/www/components/Audio/graphql/AudioQueueHooks.ts
apps/www/components/Audio/types/AudioPlayerItem.ts

feat(AudioCover): implements audiocover

---

packages/backend-modules/assets/express/pdf.js

`returnImage` expects size option to contain dimensions, not a string like "A4"
Fixes #237

fix(assets): pass necessary params to PDF endpoint, rest to asset server

---

apps/www/components/ActionBar/AudioInfo.js
apps/www/components/ActionBar/index.js
apps/www/components/Article/Page.js
apps/www/components/Audio/AudioPlayer/AudioPlaybackElement.tsx
apps/www/components/Audio/AudioPlayer/ui/tabs/latest/LatestArticleItem.tsx
apps/www/components/Audio/AudioPlayer/ui/tabs/queue/Queue.tsx
apps/www/components/Audio/AudioPlayerController.tsx
apps/www/components/Audio/AudioProvider.tsx
apps/www/components/Audio/LegacyAudioPlayer/LegacyAudioPlayer.tsx
apps/www/components/Audio/constants.ts
apps/www/components/Audio/hooks/useAudioQueue.tsx
apps/www/components/Audio/types/AudioActionTracking.ts
apps/www/components/Audio/types/AudioTracking.ts
apps/www/components/Front/index.js
apps/www/components/Marketing/Carousel.tsx
apps/www/components/Marketing/Top.tsx

- refactor(www/audio): enhance Tracking of AudioPlayer actions
- refactor(www/audio): remove redundant logs
- fix(www/actionbar): make synthetic play-button an actual button
- fix(www/marketing): faulty css in Top.tsx

refactor(www/audio): improve AudioPlayer action tracking

---

apps/admin/components/Users/Dialog/DiscussionSuspensions.js

Adds UI to suspend/unsuspend users and provide a time and reason along with it.

feat(admin): Suspension UI

---

README.md
apps/www/README.md

docs: add documentation on how to setup the authentication env-variables

---

apps/www/components/Sections/Featured.js
apps/www/lib/translations.json

feat(Nav): add vote link to search nav

---

apps/www/lib/translations.json
packages/styleguide/src/lib/translations.json

Rename «Anstössigen Inhalt melden» to «Moderation herbeirufen»

rename comment action

---

packages/backend-modules/calendar/graphql/resolvers/Calendar.js
packages/backend-modules/calendar/graphql/resolvers/_mutations/bookCalendarSlot.js
packages/backend-modules/calendar/graphql/resolvers/_mutations/cancelCalendarSlot.js
packages/backend-modules/calendar/graphql/schema-types.js
packages/backend-modules/calendar/lib/utils.ts
packages/backend-modules/calendar/migrations/sqls/20221126094529-limit-slots-per-key-down.sql
packages/backend-modules/calendar/migrations/sqls/20221126094529-limit-slots-per-key-up.sql
packages/backend-modules/migrations/migrations/20221126094529-limit-slots-per-key.js
packages/backend-modules/translate/translations.json

- [fix(calendar): allow user to cancel regardless others](https://github.com/republik/plattform/commit/02b391244026c6894fc0950bb30d74d688b689ea)
- [fix(calendar): check if user can book again](https://github.com/republik/plattform/commit/88a5e905af3f3cb891c6545e279cce99d0fae01b)
- [fix(calendar): introduce limit slots per key flag](https://github.com/republik/plattform/commit/3357981b3217d20d1d934858fe0cf03f05dc2704)
- [fix(calendar): include user ID in stringified entity IDs](https://github.com/republik/plattform/commit/c51f6db6f677f2daa04788a302e4c9547d421015)
- [fix(calendar): expose CalendarSlot.users](https://github.com/republik/plattform/commit/d1e1becb5397212a4552da085ad5378fe6f8f8f2)

Calendar, CalendarSlot improvements

---

apps/www/components/Profile/Contact.js
apps/www/components/Profile/Edit.js
apps/www/components/Profile/Page.js
apps/www/lib/translations.json
packages/backend-modules/migrations/migrations/20221213141806-add-prolitteris-id.js
packages/backend-modules/republik-crowdfundings/graphql/resolvers/_mutations/mergeUsers.js
packages/backend-modules/republik/graphql/resolvers/User.js
packages/backend-modules/republik/graphql/resolvers/_mutations/updateMe.js
packages/backend-modules/republik/graphql/schema-types.js
packages/backend-modules/republik/graphql/schema.js
packages/backend-modules/republik/migrations/sqls/20221213141806-add-prolitteris-id-down.sql
packages/backend-modules/republik/migrations/sqls/20221213141806-add-prolitteris-id-up.sql
packages/backend-modules/republik/script/gdpr/extractPersonalData.js
packages/backend-modules/translate/translations.json

feat(User): add prolitterisId to user

---

apps/www/components/Pledge/Merci.js

fix(Merci): remove long lead text in prolong merci

---

apps/www/components/ActionBar/index.js

Quick fix until we have a true action bar revamp

fix(ActionBar): flex-warp for seriesEpisode

---

packages/backend-modules/auth/graphql/resolvers/_queries/unauthorizedSession.js
packages/backend-modules/auth/lib/Users.js
packages/backend-modules/auth/lib/challenges/EmailTokenChallenge.js

This Pull Request validates tokens with payload _and_ email address.

Fix Token Validation

---

apps/www/components/Climatelab/Postcard/PostcardPreview.js

fix(www/postcard): add max-height to postcard text field

---

packages/backend-modules/access/lib/constraints/limitGrants.js
packages/backend-modules/access/lib/constraints/limitRevokedSlots.js
packages/backend-modules/access/lib/constraints/limitSlots.js
packages/backend-modules/access/lib/constraints/recipientInNoSlot.js
packages/backend-modules/access/lib/constraints/requireExistingGrants.js
packages/backend-modules/access/lib/constraints/requireGiftableMembership.js
packages/backend-modules/access/lib/constraints/requirePackage.js
packages/backend-modules/access/lib/grants.js
packages/backend-modules/access/package.json
packages/backend-modules/auth/graphql/resolvers/_mutations/updateEmail.js
packages/backend-modules/auth/lib/Users.js
packages/backend-modules/republik-crowdfundings/graphql/resolvers/_mutations/submitPledge.js
packages/backend-modules/republik-crowdfundings/lib/generateMemberships.js
packages/backend-modules/republik-crowdfundings/package.json
packages/backend-modules/republik/graphql/resolvers/_mutations/requestNewsletterSubscription.js
packages/backend-modules/republik/graphql/resolvers/_mutations/updateNewsletterSubscription.js

Avoids unprepared SQL statements and validates email from user inputs.

Harden qry stmts, validate email inputs

---

apps/www/components/Article/Page.js
apps/www/components/Article/PayNote.js

This code isn't useful anymore, since we use a fully custom paynote for the flyer.

fix(Paynote): remove unused flyer code

---

apps/www/components/FutureCampaign/SenderPage/InviteSenderPage.tsx

Show some feedback when copy to clipboard works (or doesn't!)

fix(SenderPage): copy to clipboard feedback

---

apps/admin/components/Users/Links.js
apps/admin/components/Users/Memberships/index.js
apps/admin/pages/users/[userId].js

This Pull Request adds a section with user-specific "magic links".

Admin-Tool: Magic Links as Section

---

package.json
turbo.json
yarn.lock

- chore: update turbo to v1.7.4
- chore: make dev-task 'persistent'

chore: update turbo to v1.7.4

---

apps/www/components/FutureCampaign/ReceiverPage/PriceSlider/config.ts

This reverts commit cd0f20b6d4204fb23f86076313afa28a04da624e.

feat(future-campaign): revert average-price to 120 CHF

---

apps/www/components/Climatelab/Questionnaire/Person.js
apps/www/components/Questionnaire/Questionnaire.js
apps/www/components/Questionnaire/enhancers.js
packages/backend-modules/voting/graphql/resolvers/Questionnaire.js
packages/backend-modules/voting/graphql/schema-types.js
packages/backend-modules/voting/lib/Submission.js
packages/backend-modules/voting/lib/queries.js

This Pull Request exposes [`Questionnaire.userSubmissionId`](https://github.com/republik/plattform/commit/630a16624b055aa1d01b7c40cb413544b221adbc) and implements logic in [Questionnaire](https://github.com/republik/plattform/commit/c973f0de04e74cd770de137c8316093ab522ba38) component.
A submitted questionnaire is not immediatly retrievable via ElasticSearce. To circumvent a race condition, we fetch on `Questionnaire.submissions` a submission via loader if only `id` filter is present.

Klimafragen wrap up

---

docs/.eslintrc.js
docs/next-env.d.ts
docs/next.config.mjs
docs/package.json
docs/pages/_app.mdx
docs/pages/index.mdx
docs/theme.config.tsx
docs/tsconfig.json
package.json
packages/backend-modules/search/package.json
scripts/prune.sh
yarn.lock

Adds a new top-level package based on [Nextra](https://nextra.site/) for the new docs.

Docs Setup

---

packages/styleguide/src/components/Flyer/index.tsx

We increased the character limit.

fix(Journal): increase character limit from 800 to 2500

---

packages/backend-modules/mail/templates/future_campaign_sender_reward.html
packages/backend-modules/mail/templates/future_campaign_sender_reward.txt
packages/backend-modules/translate/translations.json

Shiny news texts for the 5-years campaign.

Transactional edits

---

packages/backend-modules/republik/script/gdpr/extractPersonalData.js

This Pull Request extends script to export personal data with these database tables:
- userAttributes
- calendarSlots
- discussionSuspensions
- mailchimpLog
- stripeCustomers

fix(republik): extractPersonalData, add additional tables

---

apps/www/package.json
yarn.lock

Adds sharp as a production dependency to our main frontend. (See the explanation [here](https://nextjs.org/docs/messages/install-sharp))

fix(www): add sharp as a dependency for image optimization in production

---

apps/www/components/Crowdfunding/Status.js
apps/www/lib/translations.json
apps/www/pages/cockpit.js

fix(Cockpit): remove growth-goal

---

packages/backend-modules/documents/lib/common/meta.js
packages/backend-modules/publikator/.gitignore
packages/backend-modules/publikator/graphql/resolvers/_mutations/publish.js
packages/backend-modules/publikator/lib/auphonic/index.ts

This Pull Request will create or update an audio production on Auphonic on publish.

fix(publikator): upsert Auphonic production on publish

---

apps/www/components/Stepper/Steps.tsx
apps/www/package.json
yarn.lock

chore(deps): upgrade framer-motion

---

apps/www/components/Pledge/Submit.js
packages/backend-modules/republik-crowdfundings/graphql/resolvers/_mutations/submitPledge.js

- fix(www): wait for contactState change
- fix(republik-crowdfundings): check email if pledge.user is provided

fix(www): wait for contactState change

---

apps/www/lib/translations.json
packages/backend-modules/mail/templates/access_recipient_onboarding_klimalabor.html
packages/backend-modules/mail/templates/access_recipient_onboarding_klimalabor.txt
packages/backend-modules/mail/templates/cf_comment_notification_new.txt

- feat(www/climatelab): update landing-page texts
- feat(www/climatelab): update onboarding page texts
- feat(Climatelab): update climate lab onboarding transactional
- fix(Climatelab): fix typos and link to article
- fix(Climatelab): generate txt files for transactionals

feat(climatelab): update landing-page, onboarding page and onboarding email texts

---

packages/backend-modules/calendar/graphql/resolvers/Calendar.js
packages/backend-modules/calendar/graphql/resolvers/_mutations/bookCalendarSlot.js
packages/backend-modules/calendar/graphql/resolvers/_mutations/cancelCalendarSlot.js
packages/backend-modules/calendar/migrations/sqls/20230630094016-limit-weekdays-down.sql
packages/backend-modules/calendar/migrations/sqls/20230630094016-limit-weekdays-up.sql
packages/backend-modules/migrations/migrations/20230630094016-limit-weekdays.js

This Pull Request allows to limit available calendar slots to weekdays e.g. Monday to Saturday, but not Sundays.

fix(calendar): add weekday limitation attribute

---

packages/backend-modules/calendar/graphql/resolvers/Calendar.js
packages/backend-modules/calendar/graphql/resolvers/_mutations/bookCalendarSlot.js
packages/backend-modules/calendar/graphql/resolvers/_mutations/cancelCalendarSlot.js
packages/backend-modules/calendar/lib/utils.ts
packages/backend-modules/translate/translations.json

This Pull Requests improves calendar package:
- check when booking or cancelling if slot is in future
- move `CalendarSlot` evaluation into lib/utils
- `CalendarSlot.id` depending on context user

fix(calendar): improve book, cancel slots

---

apps/www/components/Sections/Featured.js
apps/www/lib/translations.json

Adds link to «Urabstimmung» in the featured section in nav
Todos:

chore: add vote link to nav

---

.github/workflows/test.yml
package.json
turbo.json
yarn.lock

- chore: add 'start' task to turbo-pipelines
- chore: bump to turbo@1.10.12

chore: update turborepo to v1.10.12

---

apps/www/public/robots.txt

Source: https://platform.openai.com/docs/gptbot

feat(www): forbid GPTBot useragent to access any page

---

apps/admin/lib/translations.json

Adds a label to wdwww nl in admin tool

fix(admin): label wdwww newsletter

---

apps/publikator/package.json
apps/www/package.json
packages/backend-modules/translate/package.json
packages/styleguide/package.json

Replaces old translation sheets which where not included in our organization and thus changes the according sheet keys

chore(translations): new gsheets for translations

---

.github/workflows/test.yml
apps/www/package.json
apps/www/panda.config.ts
apps/www/src/app/challenge-accepted/page.tsx
apps/www/src/app/layout.tsx
apps/www/src/components/ca-newsletter-sign-up.tsx
apps/www/src/graphql/republik-api/me.query.ts
apps/www/src/graphql/republik-api/newsletter.mutation.ts
apps/www/src/graphql/republik-api/newsletter.query.ts
apps/www/src/lib/apollo/client.ts
apps/www/src/lib/apollo/provider.tsx
apps/www/src/lib/auth/me.ts
apps/www/src/theme/preset.ts
package.json
yarn.lock

- feat(new-hope): add zod + react-hook-form
- feat(new-hope): setup apollo to allow for using apollo-hooks in client components
- feat(new-hope): first implemenation of CA NewsletterSignUp
- feat(new-hope): don't show the newsletter sign-up coponent if the user is already subscribed

feat(new-hope): implement Newsletter signup

---

apps/www/components/Article/Page.js
apps/www/components/Audio/AudioPlayer/ArticleAudioPlayer.tsx
apps/www/next-env.d.ts
apps/www/tsconfig.json

This PR enhances the ArticleAudioPlayer component to also be rendered when no audio source is available yet, but the text will be read aloud:

feat(www): update ArticleAudioPlayer to render if no audio-source is provided yet, but will be readaloud

---

apps/publikator/components/editor/modules/author/ui.js
packages/styleguide/src/templates/shared/email/components/Author.tsx

Adds new Large Variant to Email Author: 
ToDo:
-[] Test Mailchimp

feat(Author): email author variant

---

scripts/prune.sh

Fix turbo version to be used in prune step to 1.10.12 until the issue in the latest turbo version is fixed, probably related to this issue: https://github.com/vercel/turbo/issues/7188

Temp fix for problem with turbo prune 

---

apps/admin/components/Users/Roles.js
packages/backend-modules/auth/lib/Roles.js
packages/backend-modules/republik/graphql/resolvers/User.js

Authors should be able to have a public profile even if they don't have an active subscription.

feat(auth): add author role

---

apps/www/src/app/(campaign)/jetzt/[code]/generate-share-image.tsx
apps/www/src/app/(campaign)/jetzt/[code]/layout.tsx
apps/www/src/app/(campaign)/jetzt/[code]/page.tsx
apps/www/src/app/(campaign)/jetzt/angebot/page.tsx
apps/www/src/app/(campaign)/jetzt/call-to-action.tsx
apps/www/src/app/(campaign)/jetzt/justiz/page.tsx
apps/www/src/app/(campaign)/jetzt/layout.tsx
apps/www/src/app/(campaign)/jetzt/opengraph-image.tsx
apps/www/src/app/(campaign)/jetzt/page.tsx
apps/www/src/app/(campaign)/jetzt/vorgelesen/page.tsx

Campaign Audio Promo Pages

---

apps/www/components/Track.js
apps/www/components/VerlegerKampagne/VerlegerKampagneBanner.tsx
apps/www/src/app/(campaign)/jetzt/[code]/angebot/price-selection.tsx
apps/www/src/app/(campaign)/jetzt/justiz/page.tsx
apps/www/src/app/(campaign)/jetzt/vorgelesen/page.tsx

The checkout page will record UTM params in the pledge payload.
Bonus fix for conversion payload store which was broken for a while.

Pass Campaign UTM Params to Checkout

---

apps/www/components/ActionBar/UserProgress.js

Changes the behavior of the UserProgress component. Instead of showing the latest percentage, the component shows the max position.

feat(UserProgress): persist max value

---

scripts/download-geoip-data.sh

fix(maxmind-download): follow redirects

---

packages/backend-modules/mail/templates/election_candidacy_confirmation_gen24m.html

Test Email: https://api.republik.love/mail/render/election_candidacy_confirmation_gen24m

fix: adapt candidacy email

---

apps/publikator/components/Publication/useValidation.tsx
apps/publikator/components/editor/modules/paragraph/ui.js
apps/publikator/lib/translations.json
apps/www/lib/translations.json
packages/backend-modules/publikator/lib/Derivative/SyntheticReadAloud.ts

When synthetic audio is played, we set the text to "diesen Beitrag anhören"
- do not generate audio if suppressSyntheticReadAloud is set

Synthetic voice: post release fixes

---

apps/www/components/ActionBar/index.js
packages/backend-modules/documents/lib/mdast/resolve.js
packages/styleguide/src/templates/shared/audio.js

- fix play buttons in feed
- fix play buttons on the front

Play buttons

---

packages/backend-modules/migrations/migrations/20240923154325-payments-charges.js
packages/backend-modules/payments/lib/database/PgPaypmentsRepo.ts
packages/backend-modules/payments/lib/database/repo.ts
packages/backend-modules/payments/lib/handlers/stripe/chargeRefunded.ts
packages/backend-modules/payments/lib/handlers/stripe/checkoutCompleted.ts
packages/backend-modules/payments/lib/handlers/stripe/invoicePaymentSucceded.ts
packages/backend-modules/payments/lib/payments.ts
packages/backend-modules/payments/lib/providers/base.ts
packages/backend-modules/payments/lib/providers/stripe.ts
packages/backend-modules/payments/lib/types.ts
packages/backend-modules/payments/lib/workers/StripeWebhookWorker.ts
packages/backend-modules/payments/migrations/sql/20240923154325-payments-charges-down.sql
packages/backend-modules/payments/migrations/sql/20240923154325-payments-charges-up.sql

feat(payments): add charge/refund tracking for new subscriptions

---

apps/www/components/Frame/User.js

fix: swap usericon for login prompt

---

packages/backend-modules/base/__tests__/corsRegex.u.jest.js
packages/backend-modules/base/lib/corsRegex.js

Prevents the usage of domains for cors headers containing localhost outside dev envs

fix(cors): validation for localhost cors headers

---

apps/www/components/Audio/AudioPlayer/controls/PlaybackRateControl.tsx

Users requested more granluar playback rates, which is easy to do. 
Tested locally.

feat: add more granular slow speeds

---

apps/www/components/Marketing/Reasons.tsx

feat: replace old offer buttons with new paynote

---

apps/www/lib/translations.json
packages/backend-modules/republik/lib/slack.js

This PR changes to minor things.
Last sentence of [description of benefactor abo](https://www.republik.ch/angebote?package=BENEFACTOR):
Instead of 
> [...] schicken wir Ihnen das Start-up-Verleger-Paket zu.
we use
> [...] schicken wir Ihnen ein kleines Dankeschön zu.
To better distinguish reports of comments and users in Slack we use another icon when users are getting reported.

Chore small improvements

---

apps/publikator/components/editor/index.js
apps/publikator/components/editor/modules/embeddatawrapper/EditOverlay.js
apps/publikator/components/editor/modules/embeddatawrapper/index.js
apps/publikator/components/editor/modules/embeddatawrapper/ui.js
apps/publikator/components/theme-provider.tsx
apps/publikator/package.json
apps/publikator/pages/repo/[owner]/[repo]/edit.js
apps/publikator/pages/repo/[owner]/[repo]/preview.js
apps/www/next-env.d.ts
packages/styleguide/.eslintrc.js
packages/styleguide/package.json
packages/styleguide/src/components/Datawrapper/index.js
packages/styleguide/src/templates/Article/index.js

What work:
What doesn't work:
... Upon inspection, code looks as it should (same as embed code) though, but a priori this needs some tuning still...
Motivational pictures

Datawrapper

---

apps/www/components/Frame/Header.js
apps/www/src/components/paynote-overlay/paynote-overlay.tsx

- remove paynote from print
- show republik header in print
- fix typescript issue with closeHandler assignment

fix: more media print fixes

---

packages/backend-modules/voting/scripts/syncCandidacies.js

Minimal update to the sync script to only update candidacies for a given election

chore(votings): only sync candidacy statements for a given election

---

apps/www/.env.example
apps/www/middleware.ts

This would allow us to define IP addresses to block in a comma seperated IP_BLOCKLIST env variable

feat: ip blocklist middleware

---

apps/www/components/Pledge/CustomizePackage.js

Tried to solve it by setting fixedPrice to false in database, but that doesn't seem to have an effect. So removing it hardcoded.

No upsells for gifts

---

apps/www/components/Profile/ProfileView/ProfileUrls.tsx
apps/www/components/Profile/ProfileView/index.js

fix: add back admin button, linkedin username regex

---

apps/www/components/Footer/index.js
apps/www/src/components/layout/footer/index.tsx
packages/styleguide/src/components/IconButton/index.tsx

- Social media icon colors
- Consistent logo layout between app/pages footer

Footer Style Fixes

---

apps/www/components/Questionnaire/Submissions/components/AnswersGrid.tsx

feat(Questionnaire): fix layout

---

apps/www/components/Article/Page.js
apps/www/components/Questionnaire/InstantSurvey.js
apps/www/components/Questionnaire/Questionnaire.js
apps/www/components/Questionnaire/enhancers.js
apps/www/lib/translations.json

Instant survey

---

packages/backend-modules/auth/lib/Users.js
packages/backend-modules/push-notifications/lib/firebase.js
packages/backend-modules/push-notifications/package.json
yarn.lock

Attempt to fix the firebase push

fix: update firebase sdk

---

apps/www/components/Notifications/NotificationFeed.js
apps/www/components/Notifications/index.js
apps/www/lib/translations.json

add button to mark all notifications as read (readers' request)

Mark notifications as read

---

apps/www/lib/translations.json
apps/www/pages/konto/index.js

add link to account deletion page to /konto

---

apps/www/src/components/paynote-overlay/paynote-overlay.tsx

removes the current job add https://republik.ch/2025/04/30/stellenausschreibung-trainee-unternehmensmanagement from paynotes.

remove current job add (hotfix)

---

apps/www/components/Frame/SecondaryNav.js
apps/www/components/Front/index.js
apps/www/lib/context/MeContext.tsx
apps/www/lib/hooks/useProlitterisTracking.ts

This only shows play buttons on the front for people with the member role (which is everyone with a trial or a membership).

remove audio player button on front, fix prolitteris tracking

---

apps/www/src/components/auth/login/index.tsx
apps/www/src/components/auth/login/tos.tsx
apps/www/src/components/paynotes/regwall/index.tsx
apps/www/src/components/ui/form.tsx

- Use label instead of placeholder on email field
- Tweak line heights a bit

fix: style tweaks on regwall login form

---

packages/backend-modules/republik/graphql/resolvers/_queries/nextStatement.js
packages/backend-modules/republik/graphql/resolvers/_queries/statements.js

Fixes BB report ID:cmbk2g9ct001590tsuj0txa9d

fix: prevent private profiles from showing up in statements

---

packages/backend-modules/discussions/graphql/resolvers/_queries/discussion.js
packages/backend-modules/discussions/graphql/schema.js
packages/backend-modules/discussions/loaders/Discussion.js

extends the path query to allow querying discussions by path string

Allow querying discussions by path.

---

apps/www/src/app/api/(sitemaps)/[year]/sitemap/route.ts

The current implementation gives precedence to the `lastPublishedAt` field for determinig the "lastmod" tag in the sitemap. However this can be before the `publishDate`, since e.g. articles are "published" on friday for monday. So the articles appear older in the sitemap that they really are. Now it takes the more recent of the two. 
Before:
`<url>
<loc>
https://www.republik.ch/2025/06/16/microsoft-es-knallt-in-den-kantonen
</loc>
<lastmod>2025-06-14T15:24:08.012Z</lastmod>
</url>`
After:
`<url>
<loc>
http://localhost:3010/2025/06/16/microsoft-es-knallt-in-den-kantonen
</loc>
<lastmod>2025-06-16T02:50:00.000Z</lastmod>
</url>`

Fix sitemap lastmod date

---

apps/www/components/Profile/EditProfile/index.js
apps/www/components/Profile/ProfileView/index.js
apps/www/components/Profile/index.tsx

fix paynote overlapping save and cancel button on profile

---

apps/www/components/Audio/helpers/getImageCropURL.ts
apps/www/components/Audio/hooks/useAudioQueue.tsx
apps/www/components/Audio/shared/TeaserAudioPlayButton.tsx

Just fixing a few things that popped up in Sentry

Audio Player Bugfixes

---

apps/www/components/Audio/AudioPlayer/ExpandedAudioPlayer.tsx

results in two column layout for audio player (only innativeapp and in landscape mode)

fix landscape mode in native app

---

packages/backend-modules/base/express/graphql.js
packages/backend-modules/logger/lib/logger.ts

fix: ensure user id is present on gql error logs

---

apps/www/components/ChallengeAccepted/ChallengeAcceptedInlineTeaser.tsx

from 15'000 to 20'000 subscribers, yay!

increment subscribers number
